//! Hopfield Network FPGA Export
//!
//! Generates synthesizable Verilog for a Hopfield associative memory network.
//! This demonstrates the path from GPU simulation to FPGA hardware.
//!
//! Run with: cargo run --release --features fpga --example hopfield_fpga_export

#[cfg(feature = "fpga")]
fn main() {
    use std::fs::File;
    use std::io::Write;

    println!("=== Hopfield Network FPGA Export ===\n");

    // Generate different sizes
    for &size in &[4, 8, 16, 32] {
        println!(
            "--- Generating {}x{} Hopfield Network ({} neurons) ---\n",
            size,
            size,
            size * size
        );

        let verilog = generate_hopfield_verilog(size);
        let filename = format!("hopfield_{}x{}.v", size, size);

        let mut file = File::create(&filename).expect("Failed to create file");
        file.write_all(verilog.as_bytes()).expect("Failed to write");

        println!("  Written to: {}", filename);

        // Resource estimates
        let resources = estimate_hopfield_resources(size);
        println!("  Estimated resources:");
        println!("    - Flip-flops: {}", resources.flip_flops);
        println!("    - LUTs: {}", resources.luts);
        println!("    - BRAM 18Kb: {}", resources.bram);
        println!("    - Est. Fmax: {} MHz", resources.fmax_mhz);
        println!(
            "    - Throughput: {:.2} Gspins/sec @ Fmax",
            (size * size) as f64 * resources.fmax_mhz as f64 / 1000.0
        );
        println!();
    }

    // Generate a detailed 8x8 with testbench
    println!("--- Generating 8x8 with Testbench ---\n");
    let verilog = generate_hopfield_verilog(8);
    let testbench = generate_hopfield_testbench(8);

    let mut file = File::create("hopfield_8x8_full.v").expect("create");
    file.write_all(verilog.as_bytes()).expect("write");
    file.write_all(b"\n\n").expect("write");
    file.write_all(testbench.as_bytes()).expect("write");

    println!("  Written: hopfield_8x8_full.v (with testbench)");
    println!();

    // Show snippet of generated Verilog
    println!("--- Sample Verilog (first 80 lines) ---\n");
    for (i, line) in verilog.lines().take(80).enumerate() {
        println!("{:3}: {}", i + 1, line);
    }
    println!("  ... ({} total lines)\n", verilog.lines().count());

    // Synthesis instructions
    println!("=== Synthesis Instructions ===\n");
    println!("For Lattice ECP5 (open source toolchain):");
    println!(
        "  yosys -p \"read_verilog hopfield_8x8.v; synth_ecp5 -top hopfield_8x8; write_json hopfield.json\""
    );
    println!("  nextpnr-ecp5 --json hopfield.json --lpf pins.lpf --textcfg hopfield.txt");
    println!("  ecppack hopfield.txt hopfield.bit");
    println!();
    println!("For Xilinx (Vivado):");
    println!("  1. Create project, add hopfield_8x8.v");
    println!("  2. Run synthesis, implementation");
    println!("  3. Check timing report for Fmax");
    println!();

    println!("=== Export Complete ===");
}

/// Resource estimate for FPGA
struct FpgaResources {
    flip_flops: usize,
    luts: usize,
    bram: usize,
    fmax_mhz: usize,
}

/// Estimate FPGA resources for NxN Hopfield network
fn estimate_hopfield_resources(n: usize) -> FpgaResources {
    let neurons = n * n;

    // Each neuron needs:
    // - 1 FF for spin state
    // - ~4 LUTs for neighbor sum logic (nearest neighbor)
    // - ~2 LUTs for threshold comparison
    // - ~2 LUTs for LFSR contribution (if stochastic)

    let flip_flops = neurons + 32; // neurons + LFSR
    let luts_per_neuron = 8;
    let luts = neurons * luts_per_neuron + 64; // overhead for LFSR, control

    // BRAM only needed for larger networks (weight storage)
    let bram = if neurons > 1024 {
        (neurons * 4) / 18432 + 1
    } else {
        0
    };

    // Fmax estimate based on critical path (neighbor access + sum + compare)
    // Smaller networks can run faster
    let fmax_mhz = match n {
        1..=8 => 400,
        9..=16 => 300,
        17..=32 => 200,
        33..=64 => 150,
        _ => 100,
    };

    FpgaResources {
        flip_flops,
        luts,
        bram,
        fmax_mhz,
    }
}

/// Generate Verilog for an NxN Hopfield network (lattice topology)
fn generate_hopfield_verilog(n: usize) -> String {
    let mut v = String::new();

    // Header
    v.push_str(&format!(
        r#"// ============================================================================
// Hopfield Associative Memory Network - {}x{} ({} neurons)
// Generated by TileUniverse FPGA Export
//
// Architecture: 2D lattice with nearest-neighbor couplings
// Update rule: Synchronous, deterministic sign(sum(J_ij * s_j))
// Coupling: Antiferromagnetic (J = -1) for checkerboard ground state
// ============================================================================

module hopfield_{}x{} (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        enable,        // Enable updates
    input  wire [{}:0] init_pattern,  // Initial pattern to load
    input  wire        load,          // Load initial pattern
    output wire [{}:0] state,         // Current network state
    output wire        stable         // Network has converged
);

    // ========================================================================
    // Neuron state registers (1 bit per neuron, +1 = 1, -1 = 0)
    // ========================================================================
"#,
        n,
        n,
        n * n,
        n,
        n,
        n * n - 1,
        n * n - 1
    ));

    // State registers
    v.push_str(&format!("    reg [{}:0] spins;\n", n * n - 1));
    v.push_str(&format!("    reg [{}:0] spins_prev;\n", n * n - 1));
    v.push_str("    reg stable_reg;\n\n");

    // Output assignments
    v.push_str("    assign state = spins;\n");
    v.push_str("    assign stable = stable_reg;\n\n");

    // Local field computation for each neuron
    v.push_str("    // ========================================================================\n");
    v.push_str("    // Local field computation: h_i = sum_j(J_ij * s_j)\n");
    v.push_str("    // For antiferromagnetic coupling (J=-1): h_i = -(neighbor sum)\n");
    v.push_str("    // New spin = sign(h_i) => 1 if h_i > 0, else 0\n");
    v.push_str("    // With J=-1: s_i = 1 if (sum of neighbors) < 0 (i.e., more 0s than 1s)\n");
    v.push_str(
        "    // ========================================================================\n\n",
    );

    v.push_str(&format!("    wire [{}:0] next_spins;\n\n", n * n - 1));

    // Generate update logic for each neuron
    for y in 0..n {
        for x in 0..n {
            let idx = y * n + x;
            let mut neighbors = Vec::new();

            // Collect neighbor indices (with wrapping for periodic boundary)
            // Left
            if x > 0 {
                neighbors.push(y * n + (x - 1));
            }
            // Right
            if x < n - 1 {
                neighbors.push(y * n + (x + 1));
            }
            // Up
            if y > 0 {
                neighbors.push((y - 1) * n + x);
            }
            // Down
            if y < n - 1 {
                neighbors.push((y + 1) * n + x);
            }

            if neighbors.is_empty() {
                v.push_str(&format!(
                    "    assign next_spins[{}] = spins[{}]; // corner, no neighbors\n",
                    idx, idx
                ));
            } else {
                // For antiferromagnetic: new_spin = NOT(majority of neighbors)
                // sum > 2 means majority are 1s, so we should be 0
                // Using: if sum >= 2 (for 4 neighbors), output 0, else 1
                let neighbor_bits: Vec<String> =
                    neighbors.iter().map(|&i| format!("spins[{}]", i)).collect();
                let sum_expr = neighbor_bits.join(" + ");
                let threshold = (neighbors.len() + 1) / 2; // Majority threshold

                v.push_str(&format!(
                    "    assign next_spins[{}] = ({}) < {} ? 1'b1 : 1'b0; // ({},{})\n",
                    idx, sum_expr, threshold, x, y
                ));
            }
        }
    }

    // Sequential update logic
    v.push_str(&format!(
        r#"
    // ========================================================================
    // Sequential update logic
    // ========================================================================
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            spins <= {}'b0;
            spins_prev <= {}'b0;
            stable_reg <= 1'b0;
        end else if (load) begin
            spins <= init_pattern;
            spins_prev <= ~init_pattern; // Force unstable initially
            stable_reg <= 1'b0;
        end else if (enable) begin
            spins_prev <= spins;
            spins <= next_spins;
            // Stable when state hasn't changed
            stable_reg <= (spins == next_spins);
        end
    end

endmodule
"#,
        n * n,
        n * n
    ));

    v
}

/// Generate a simple testbench for the Hopfield network
fn generate_hopfield_testbench(n: usize) -> String {
    let neurons = n * n;

    // Create checkerboard pattern
    let mut checkerboard: u64 = 0;
    for y in 0..n {
        for x in 0..n {
            if (x + y) % 2 == 0 {
                checkerboard |= 1 << (y * n + x);
            }
        }
    }

    // Create corrupted version (flip ~30% of bits)
    let corrupted = checkerboard ^ 0x0F0F0F0F0F0F0F0F_u64; // Simple corruption pattern

    format!(
        r#"// ============================================================================
// Testbench for {}x{} Hopfield Network
// ============================================================================

`timescale 1ns / 1ps

module hopfield_{}x{}_tb;
    reg clk;
    reg rst_n;
    reg enable;
    reg [{}:0] init_pattern;
    reg load;
    wire [{}:0] state;
    wire stable;

    // Instantiate the Hopfield network
    hopfield_{}x{} uut (
        .clk(clk),
        .rst_n(rst_n),
        .enable(enable),
        .init_pattern(init_pattern),
        .load(load),
        .state(state),
        .stable(stable)
    );

    // Clock generation (100 MHz)
    initial clk = 0;
    always #5 clk = ~clk;

    // Test sequence
    initial begin
        $display("=== Hopfield {}x{} Testbench ===");

        // Initialize
        rst_n = 0;
        enable = 0;
        load = 0;
        init_pattern = 0;
        #20;

        rst_n = 1;
        #10;

        // Load corrupted checkerboard pattern
        $display("Loading corrupted pattern: %h", {});
        init_pattern = {}'h{:016X};
        load = 1;
        #10;
        load = 0;

        // Run until stable
        enable = 1;
        $display("Running network...");

        repeat (100) begin
            #10;
            if (stable) begin
                $display("Network stabilized at cycle %0d", $time/10);
                $display("Final state: %h", state);
                $display("Expected (checkerboard): %h", {}'h{:016X});
                if (state == {}'h{:016X} || state == ~({}'h{:016X}))
                    $display("SUCCESS: Pattern recovered!");
                else
                    $display("Pattern differs from expected");
                $finish;
            end
        end

        $display("Network did not stabilize in 100 cycles");
        $display("Final state: %h", state);
        $finish;
    end

endmodule
"#,
        n,
        n,
        n,
        n,
        neurons - 1,
        neurons - 1,
        n,
        n,
        n,
        n,
        corrupted,
        neurons,
        corrupted,
        neurons,
        checkerboard,
        neurons,
        checkerboard,
        neurons,
        checkerboard
    )
}

#[cfg(not(feature = "fpga"))]
fn main() {
    // When fpga feature is not enabled, we can still generate basic Verilog
    // since the generation doesn't actually depend on rust-hdl

    println!("=== Hopfield Network FPGA Export (standalone mode) ===\n");
    println!("Note: Running without 'fpga' feature - basic generation only.\n");

    // We can still generate Verilog since it's just string manipulation
    use std::fs::File;
    use std::io::Write;

    for &size in &[4, 8, 16] {
        println!("--- Generating {}x{} Hopfield Network ---", size, size);

        let verilog = generate_hopfield_verilog_standalone(size);
        let filename = format!("hopfield_{}x{}.v", size, size);

        if let Ok(mut file) = File::create(&filename) {
            let _ = file.write_all(verilog.as_bytes());
            println!("  Written to: {}", filename);
        }

        // Simple resource estimate
        let neurons = size * size;
        let ffs = neurons + 32;
        let luts = neurons * 8 + 64;
        let fmax = if size <= 8 {
            400
        } else if size <= 16 {
            300
        } else {
            200
        };

        println!("  Est. FFs: {}, LUTs: {}, Fmax: {} MHz", ffs, luts, fmax);
        println!(
            "  Throughput: {:.2} Gspins/sec\n",
            neurons as f64 * fmax as f64 / 1000.0
        );
    }

    println!("=== Export Complete ===");
}

#[cfg(not(feature = "fpga"))]
fn generate_hopfield_verilog_standalone(n: usize) -> String {
    let mut v = String::new();

    v.push_str(&format!(
        "// Hopfield {}x{} - Generated by TileUniverse
module hopfield_{}x{} (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        enable,
    input  wire [{}:0] init_pattern,
    input  wire        load,
    output wire [{}:0] state,
    output wire        stable
);
    reg [{}:0] spins;
    reg [{}:0] spins_prev;
    assign state = spins;
    assign stable = (spins == spins_prev);

    wire [{}:0] next_spins;\n\n",
        n,
        n,
        n,
        n,
        n * n - 1,
        n * n - 1,
        n * n - 1,
        n * n - 1,
        n * n - 1
    ));

    // Generate neuron logic
    for y in 0..n {
        for x in 0..n {
            let idx = y * n + x;
            let mut neighbors = Vec::new();
            if x > 0 {
                neighbors.push(y * n + (x - 1));
            }
            if x < n - 1 {
                neighbors.push(y * n + (x + 1));
            }
            if y > 0 {
                neighbors.push((y - 1) * n + x);
            }
            if y < n - 1 {
                neighbors.push((y + 1) * n + x);
            }

            if neighbors.is_empty() {
                v.push_str(&format!(
                    "    assign next_spins[{}] = spins[{}];\n",
                    idx, idx
                ));
            } else {
                let sum: Vec<String> = neighbors.iter().map(|&i| format!("spins[{}]", i)).collect();
                let thresh = (neighbors.len() + 1) / 2;
                v.push_str(&format!(
                    "    assign next_spins[{}] = ({}) < {} ? 1'b1 : 1'b0;\n",
                    idx,
                    sum.join(" + "),
                    thresh
                ));
            }
        }
    }

    v.push_str(&format!(
        "
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            spins <= 0; spins_prev <= 0;
        end else if (load) begin
            spins <= init_pattern; spins_prev <= ~init_pattern;
        end else if (enable) begin
            spins_prev <= spins; spins <= next_spins;
        end
    end
endmodule\n"
    ));

    v
}
