//! EPIC 116: TILE-8 Visualizer
//!
//! Interactive visualization of the TILE-8 CPU grid.
//! Shows gates at close zoom, CPUs at medium zoom, results at far zoom.
//!
//! Run with: cargo run --example tile8_visualizer --features visualizer --release
//!

use egui_macroquad::egui;
use macroquad::prelude::*;

// Memory diagnostics helper
fn print_memory_usage(label: &str) {
    #[cfg(target_os = "windows")]
    {
        use std::mem::MaybeUninit;
        #[repr(C)]
        struct ProcessMemoryCounters {
            cb: u32,
            page_fault_count: u32,
            peak_working_set_size: usize,
            working_set_size: usize,
            quota_peak_paged_pool_usage: usize,
            quota_paged_pool_usage: usize,
            quota_peak_non_paged_pool_usage: usize,
            quota_non_paged_pool_usage: usize,
            pagefile_usage: usize,
            peak_pagefile_usage: usize,
        }
        #[link(name = "psapi")]
        unsafe extern "system" {
            fn GetProcessMemoryInfo(
                process: *mut std::ffi::c_void,
                ppsmemCounters: *mut ProcessMemoryCounters,
                cb: u32,
            ) -> i32;
        }
        #[link(name = "kernel32")]
        unsafe extern "system" {
            fn GetCurrentProcess() -> *mut std::ffi::c_void;
        }
        unsafe {
            let mut pmc = MaybeUninit::<ProcessMemoryCounters>::zeroed().assume_init();
            pmc.cb = std::mem::size_of::<ProcessMemoryCounters>() as u32;
            if GetProcessMemoryInfo(GetCurrentProcess(), &mut pmc, pmc.cb) != 0 {
                let working_mb = pmc.working_set_size as f64 / (1024.0 * 1024.0);
                let commit_mb = pmc.pagefile_usage as f64 / (1024.0 * 1024.0);
                println!(
                    "[MEMORY] {}: Working={:.1}MB, Commit={:.1}MB",
                    label, working_mb, commit_mb
                );
            }
        }
    }
    #[cfg(not(target_os = "windows"))]
    {
        println!(
            "[MEMORY] {}: (diagnostics only available on Windows)",
            label
        );
    }
}

use engine::assembler;
use engine::slim_simulation::SlimSimulation;
use engine::tile_meta::TileType;
use engine::tile8::graph_state::{Graph, GraphStateVerification};
use engine::tile8::quantum_router_f64::{GhzVerification, QuantumGridF64};
use engine::tile8::{
    CpuInstance, calculate_grid_size, instantiate_cpus, run_all_cpus, run_all_cpus_fast,
};
#[cfg(feature = "gpu-prototype")]
use engine::tile8::{GpuCpuInstance, instantiate_cpus_gpu_direct};

// =============================================================================
// Constants
// =============================================================================

const TILE_SIZE: f32 = 10.0;
const MIN_ZOOM: f32 = 0.005;
const MAX_ZOOM: f32 = 4.0;
const ZOOM_LERP_SPEED: f32 = 12.0;
const PAN_SPEED: f32 = 800.0;
const LOD_GATES: f32 = 0.5;
const LOD_CPUS: f32 = 0.02;

fn format_thousands(n: usize) -> String {
    let s = n.to_string();
    let mut result = String::new();
    for (i, c) in s.chars().rev().enumerate() {
        if i > 0 && i % 3 == 0 {
            result.push(',');
        }
        result.push(c);
    }
    result.chars().rev().collect()
}

/// Convert a graph to OpenQASM 3.0 circuit that creates its graph state.
/// Graph state construction: H on all qubits, then CZ for each edge.
fn graph_to_qasm3(g: &Graph) -> String {
    let mut qasm = String::new();
    qasm.push_str("// Graph State Circuit (OpenQASM 3.0)\n");
    qasm.push_str("// Generated by TileUniverse Sprint 57.0\n");
    qasm.push_str(&format!(
        "// Graph: {} vertices, {} edges\n\n",
        g.n_vertices,
        g.num_edges()
    ));
    qasm.push_str("OPENQASM 3.0;\n");
    qasm.push_str("include \"stdgates.inc\";\n\n");
    qasm.push_str(&format!("qubit[{}] q;\n\n", g.n_vertices));

    // Step 1: Apply Hadamard to all qubits
    qasm.push_str("// Step 1: Initialize all qubits to |+> state\n");
    for i in 0..g.n_vertices {
        qasm.push_str(&format!("h q[{}];\n", i));
    }
    qasm.push('\n');

    // Step 2: Apply CZ for each edge
    if !g.edges.is_empty() {
        qasm.push_str("// Step 2: Apply CZ gates for graph edges\n");
        for (i, j) in &g.edges {
            qasm.push_str(&format!("cz q[{}], q[{}];\n", i, j));
        }
    }

    qasm
}

// =============================================================================
// Color Palette
// =============================================================================

const BG_COLOR: Color = Color::new(0.05, 0.05, 0.08, 1.0);
const GRID_COLOR: Color = Color::new(0.15, 0.15, 0.2, 1.0);

fn tile_type_color(tile_type: TileType, value: u64) -> Color {
    let brightness = if value > 0 { 1.0 } else { 0.4 };
    match tile_type {
        TileType::Wire => Color::new(0.3 * brightness, 0.3 * brightness, 0.35 * brightness, 1.0),
        TileType::And => Color::new(0.9 * brightness, 0.2 * brightness, 0.3 * brightness, 1.0),
        TileType::Or => Color::new(0.2 * brightness, 0.9 * brightness, 0.3 * brightness, 1.0),
        TileType::Xor => Color::new(0.3 * brightness, 0.5 * brightness, 0.95 * brightness, 1.0),
        TileType::Not => Color::new(0.95 * brightness, 0.9 * brightness, 0.2 * brightness, 1.0),
        TileType::Add => Color::new(1.0 * brightness, 0.5 * brightness, 0.1 * brightness, 1.0),
        TileType::Sub => Color::new(0.8 * brightness, 0.2 * brightness, 0.9 * brightness, 1.0),
        TileType::Mux => Color::new(0.1 * brightness, 0.9 * brightness, 0.9 * brightness, 1.0),
        TileType::Ram => Color::new(0.4 * brightness, 0.6 * brightness, 0.95 * brightness, 1.0),
        TileType::Const => Color::new(0.7 * brightness, 0.7 * brightness, 0.75 * brightness, 1.0),

        TileType::CpuHead => Color::new(0.8, 0.0, 0.8, 1.0),
        TileType::Register => Color::new(0.0, 0.8, 0.8, 1.0),
        TileType::Console => Color::new(1.0, 0.5, 0.0, 1.0),
        TileType::Selector => Color::new(0.0, 0.8, 0.3, 1.0), // Sprint 66: Green for selection

        _ => Color::new(0.2 * brightness, 0.2 * brightness, 0.25 * brightness, 1.0),
    }
}

fn tile_type_name(tile_type: TileType) -> &'static str {
    match tile_type {
        TileType::Wire => "WIRE",
        TileType::And => "AND",
        TileType::Or => "OR",
        TileType::Xor => "XOR",
        TileType::Not => "NOT",
        TileType::Add => "ADD",
        TileType::Sub => "SUB",
        TileType::Mux => "MUX",
        TileType::Ram => "RAM",
        TileType::Const => "CONST",
        TileType::CpuHead => "CPU",
        TileType::Register => "REG",
        TileType::Console => "OUT",
        TileType::Selector => "SEL",
        _ => "",
    }
}

fn value_to_heat(value: u8) -> Color {
    let v = value as f32 / 255.0;
    let hue = 0.7 - v * 0.9;
    let hue = if hue < 0.0 { hue + 1.0 } else { hue };
    let sat = 0.8;
    let val = 0.4 + v * 0.6;
    hsv_to_rgb(hue, sat, val)
}

fn cpu_color(r0: u8, cpu_id: usize, time_pulse: f32) -> Color {
    let hue = ((cpu_id * 37) % 360) as f32 / 360.0;
    let sat = 0.7 + (r0 as f32 / 255.0) * 0.3;
    let pulse = (time_pulse + (r0 as f32 / 64.0)).sin() * 0.1;
    let val = 0.5 + (r0 as f32 / 255.0) * 0.5 + pulse;
    hsv_to_rgb(hue, sat, val.clamp(0.3, 1.0))
}

/// Map probability to heatmap color (Sprint 57.0 Phase 5)
/// Uses viridis-like colormap: purple (low) -> blue -> green -> yellow (high)
fn probability_to_color(prob: f64, max_prob: f64, log_scale: bool) -> Color {
    if prob <= 0.0 {
        return Color::new(0.0, 0.0, 0.0, 0.0); // Transparent for zero
    }

    let normalized = if log_scale {
        // Log scale: better for sparse states
        let log_prob = prob.log10();
        let log_max = max_prob.log10();
        let log_min = -15.0; // ~1e-15 minimum visible
        ((log_prob - log_min) / (log_max - log_min)).clamp(0.0, 1.0)
    } else {
        // Linear scale
        (prob / max_prob).clamp(0.0, 1.0)
    };

    let t = normalized as f32;

    // Viridis-inspired colormap
    let r = (0.267 + t * (0.993 - 0.267)).clamp(0.0, 1.0);
    let g = if t < 0.5 {
        0.004 + t * 2.0 * (0.565 - 0.004)
    } else {
        0.565 + (t - 0.5) * 2.0 * (0.906 - 0.565)
    };
    let b = if t < 0.5 {
        0.329 + t * 2.0 * (0.693 - 0.329)
    } else {
        0.693 - (t - 0.5) * 2.0 * (0.693 - 0.144)
    };

    Color::new(r, g.clamp(0.0, 1.0), b.clamp(0.0, 1.0), 0.8)
}

fn hsv_to_rgb(h: f32, s: f32, v: f32) -> Color {
    let c = v * s;
    let x = c * (1.0 - ((h * 6.0) % 2.0 - 1.0).abs());
    let m = v - c;
    let (r, g, b) = match (h * 6.0) as i32 {
        0 => (c, x, 0.0),
        1 => (x, c, 0.0),
        2 => (0.0, c, x),
        3 => (0.0, x, c),
        4 => (x, 0.0, c),
        _ => (c, 0.0, x),
    };
    Color::new(r + m, g + m, b + m, 1.0)
}

// =============================================================================
// Visualizer State
// =============================================================================

#[derive(PartialEq, Clone, Copy, Debug)]
enum Tool {
    Wire,
    And,
    Or,
    Xor,
    Clock,
    Not,
    Const,
    CpuHead,
    Register,
    Console,
    Selector, // Sprint 66: Fitness-based selection
    Eraser,
}

struct Visualizer {
    // CPU mode: full simulation for execution
    #[cfg(not(feature = "gpu-prototype"))]
    sim: SlimSimulation,

    // GPU mode: just tile types for rendering (values come from GPU readback)
    #[cfg(feature = "gpu-prototype")]
    tile_types: Vec<u8>,

    #[cfg(not(feature = "gpu-prototype"))]
    cpus: Vec<CpuInstance>,

    // Camera
    camera_pos: Vec2,
    zoom: f32,
    target_zoom: f32,

    // State
    running: bool,
    show_grid: bool,
    fullscreen: bool,
    cycle_count: u64,
    time: f32,

    // Tools
    current_tool: Tool,

    // Grid info
    grid_width: usize,
    grid_height: usize,
    cpu_spacing: usize,
    _cpu_count: usize,

    // UI Interactive State
    selected_cpu_index: Option<usize>,
    speed_multiplier: usize,
    code_source: String,
    inspector_open: bool,

    #[cfg(feature = "gpu-prototype")]
    gpu_sim: Option<engine::gpu_engine::GpuSimulation>,

    // Cached GPU texture for throttled readback (satellite mode only)
    #[cfg(feature = "gpu-prototype")]
    cached_satellite_texture: Option<Texture2D>,
    // Cached ROI texture for detail mode (allows update via update_from_image to save VRAM)
    #[cfg(feature = "gpu-prototype")]
    cached_roi_texture: Option<Texture2D>,

    // Toggle for editing (drawing) vs interacting
    edit_mode: bool,

    // Last captured logic state (ROI) for Inspector/HUD
    // (x, y, w, h, data)
    #[cfg(feature = "gpu-prototype")]
    last_roi_state: Option<(u32, u32, u32, u32, Vec<u32>)>,

    #[cfg(feature = "gpu-prototype")]
    cpu_grid: VirtualCpuGrid,

    // Quantum state simulation (f64 precision for 100% fidelity)
    quantum_grid: Option<QuantumGridF64>,
    quantum_n_qubits: usize,
    quantum_verification: Option<GhzVerification>,
    quantum_panel_open: bool,

    // Graph State Builder (Sprint 57.0 Phase 4)
    graph_type: GraphPreset,
    graph_n_vertices: usize,
    graph_grid_rows: usize,
    graph_grid_cols: usize,
    graph_random_p: f64,
    graph_random_seed: u64,
    graph_current: Option<Graph>,
    graph_verification: Option<GraphStateVerification>,

    // Amplitude Heatmap (Sprint 57.0 Phase 5)
    show_amplitude_heatmap: bool,
    heatmap_log_scale: bool,
    heatmap_top_n: usize,
    heatmap_cached_probs: Option<Vec<(usize, f64)>>,
}

/// Graph type presets for graph state builder
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum GraphPreset {
    Star,
    Path,
    Cycle,
    Grid2D,
    Complete,
    Hypercube,
    Ladder,
    RandomER,
}

/// Virtual representation of the CPU grid to avoid allocating millions of structs
#[cfg(feature = "gpu-prototype")]
#[derive(Debug, Clone, Copy)]
pub struct VirtualCpuGrid {
    pub width: usize,
    pub height: usize,
    pub spacing: usize,
    pub count: usize,
    pub grid_width: usize, // Simulation grid width
}

#[cfg(feature = "gpu-prototype")]
impl VirtualCpuGrid {
    pub fn get_cpu(&self, id: usize) -> Option<GpuCpuInstance> {
        if id >= self.count {
            return None;
        }

        let cpus_per_row = (self.grid_width / self.spacing).max(1);
        let row = id / cpus_per_row;
        let col = id % cpus_per_row;
        let ox = col * self.spacing;
        let oy = row * self.spacing;

        Some(GpuCpuInstance::new(id, (ox, oy)))
    }

    pub fn get_cpu_at_tile(&self, tx: usize, ty: usize) -> Option<usize> {
        // Map tile back to nearest CPU origin
        let col = tx / self.spacing;
        let row = ty / self.spacing;
        let ox = col * self.spacing;
        let oy = row * self.spacing;

        // Check if tile is within a CPU's footprint (3x3 for dense mesh)
        if tx >= ox && tx < ox + 3 && ty >= oy && ty < oy + 3 {
            let cpus_per_row = (self.grid_width / self.spacing).max(1);
            let id = row * cpus_per_row + col;
            if id < self.count {
                return Some(id);
            }
        }
        None
    }
}

impl Visualizer {
    async fn new_with_mode(cpu_count: usize, spacing: usize, selector_mode: bool) -> Self {
        print_memory_usage("START");
        let (width, height) = calculate_grid_size(cpu_count, spacing);
        println!("Grid size: {}x{} = {} tiles", width, height, width * height);

        // Base program: Fibonacci Sequence
        let base_program = [0xA1, 0xA4, 0xAF, 0x18, 0x21, 0x16, 0xB0, 0x00];

        let initial_code = "start:\nMOV A, A ; R0=N\nMOV B, B ; R1=S\nADD A, B ; A=N+S\nMOV B, C ; R2=E\nADD A, B ; A=N+S+E\nMOV B, D ; R3=W\nADD A, B ; A=N+S+E+W\nSHR A, 2 ; A=AVG\nMOV B, A ; S=AVG\nMOV C, A ; E=AVG\nMOV D, A ; W=AVG\nJMP start";

        let center_x = (width as f32 * TILE_SIZE) / 2.0;
        let center_y = (height as f32 * TILE_SIZE) / 2.0;

        // =====================================================================
        // GPU MODE: Direct initialization - NO SlimSimulation allocation!
        // This saves ~6GB of RAM by bypassing the full simulation.
        // =====================================================================
        #[cfg(feature = "gpu-prototype")]
        let (gpu_sim, tile_types, cpu_grid) = {
            println!("GPU Direct Mode: Bypassing SlimSimulation (~6GB saved)");
            let area = width * height;
            print_memory_usage("Before tile_types alloc");

            // Create tile_types array directly (144MB for 151M tiles)
            let mut tile_types = vec![0u8; area]; // 0 = Wire (default)
            print_memory_usage("After tile_types alloc");

            // Track if we need custom state initialization
            let mut initial_state: Option<Vec<u32>> = None;

            if selector_mode {
                // SPRINT 66: Fill grid with Selector tiles for evolutionary selection
                println!(
                    "Selector Mode: Filling grid with {} Selector tiles...",
                    area
                );
                for i in 0..area {
                    tile_types[i] = 48; // Selector tile type
                }

                // Seed random initial values for evolution
                println!("Seeding random initial values...");
                let mut rng_state = 0xDEADBEEFu64;
                let mut state = Vec::with_capacity(area);
                for _ in 0..area {
                    // Simple xorshift for random values
                    rng_state ^= rng_state << 13;
                    rng_state ^= rng_state >> 7;
                    rng_state ^= rng_state << 17;
                    state.push(rng_state as u32);
                }
                initial_state = Some(state);
                println!("Selector grid ready with random genome. Evolution will be visible!");
                print_memory_usage("After Selector placement");
            } else {
                // Place CPUs directly into tile_types array (Shared Mesh Hive!)
                println!("Placing {} CPUs directly into tile array...", cpu_count);
                instantiate_cpus_gpu_direct(&mut tile_types, width, height, cpu_count, spacing);
                println!("Placed {} CPUs into tilemap.", cpu_count);
                print_memory_usage("After CPU placement");
            }

            // DIAGNOSTIC PROBE: Force a CLOCK tile at (10, 10)
            if width > 10 && height > 10 {
                let probe_idx = 10 * width + 10;
                tile_types[probe_idx] = 7; // ClockGlobal
                println!(" injected DIAGNOSTIC CLOCK at index {}", probe_idx);
            }

            // Initialize GPU
            println!("Initializing GpuSimulation...");
            let mut gpu =
                engine::gpu_engine::GpuSimulation::new(width as u32, height as u32, None).await;
            println!("GpuSimulation ready.");
            print_memory_usage("After GpuSimulation::new");

            // Upload rules and state
            if let Some(ref state) = initial_state {
                println!("Uploading rules and initial state...");
                gpu.load_state(&tile_types, state);
                print_memory_usage("After load_state");
            } else {
                gpu.load_rules_only(&tile_types);
                print_memory_usage("After load_rules_only");
            }

            // Assemble and Upload code_source (Ripple benchmark)
            // The assembler produces 4-byte GPU format instructions directly
            let initial_binary = match assembler::assemble(initial_code) {
                Ok(bin) => {
                    // Assembler output is already in GPU format - use load_rom_compiled
                    gpu.load_rom_compiled(&bin);
                    bin
                }
                Err(e) => {
                    println!("Failed to assemble initial code: {}. Using fallback.", e);
                    // Fallback is old TILE-8 8-bit format - use load_rom which compiles it
                    gpu.load_rom(&base_program);
                    base_program.to_vec()
                }
            };
            let _ = initial_binary; // Suppress unused warning
            print_memory_usage("After load_rom");

            println!(
                "Compilation Complete. {} Nodes uploaded.",
                format_thousands(area)
            );

            let cpu_grid = VirtualCpuGrid {
                width: width / spacing,
                height: height / spacing,
                spacing,
                count: cpu_count,
                grid_width: width,
            };

            (Some(gpu), tile_types, cpu_grid)
        };

        // =====================================================================
        // CPU MODE: Full SlimSimulation (needed for CPU-side execution)
        // =====================================================================
        #[cfg(not(feature = "gpu-prototype"))]
        let (cpus, sim) = {
            let mut sim = SlimSimulation::with_size(width, height);
            let cpus = instantiate_cpus(&mut sim, cpu_count, spacing, &base_program);
            (cpus, sim)
        };

        print_memory_usage("Before constructing Visualizer struct");
        let result = Self {
            #[cfg(not(feature = "gpu-prototype"))]
            sim,
            #[cfg(feature = "gpu-prototype")]
            tile_types,
            #[cfg(feature = "gpu-prototype")]
            cached_satellite_texture: None,
            #[cfg(feature = "gpu-prototype")]
            cached_roi_texture: None,

            #[cfg(not(feature = "gpu-prototype"))]
            cpus,

            #[cfg(feature = "gpu-prototype")]
            cpu_grid,

            camera_pos: vec2(center_x, center_y),
            zoom: 0.008,
            target_zoom: 0.008,
            running: false,
            show_grid: true,
            fullscreen: false,
            cycle_count: 16,
            time: 0.0,
            grid_width: width,
            grid_height: height,
            cpu_spacing: spacing,
            _cpu_count: cpu_count,
            selected_cpu_index: None,
            speed_multiplier: 30, // Default to 30x steps per frame for throughput
            inspector_open: true,
            code_source: initial_code.to_string(),
            current_tool: Tool::Wire,
            #[cfg(feature = "gpu-prototype")]
            gpu_sim,

            edit_mode: false,
            #[cfg(feature = "gpu-prototype")]
            last_roi_state: None,

            // Initialize quantum state (default: 14 qubits for reasonable demo)
            quantum_grid: None,
            quantum_n_qubits: 14,
            quantum_verification: None,
            quantum_panel_open: true,

            // Graph state builder (Sprint 57.0 Phase 4)
            graph_type: GraphPreset::Star,
            graph_n_vertices: 8,
            graph_grid_rows: 4,
            graph_grid_cols: 4,
            graph_random_p: 0.3,
            graph_random_seed: 42,
            graph_current: None,
            graph_verification: None,

            // Amplitude heatmap (Sprint 57.0 Phase 5)
            show_amplitude_heatmap: false,
            heatmap_log_scale: true,
            heatmap_top_n: 100,
            heatmap_cached_probs: None,
        };
        print_memory_usage("FINAL (Visualizer constructed)");
        result
    }

    // Helper: Get tile type (works in both GPU and CPU mode)
    #[inline]
    fn get_tile_type_at(&self, x: usize, y: usize) -> TileType {
        #[cfg(feature = "gpu-prototype")]
        {
            let idx = y * self.grid_width + x;
            if idx < self.tile_types.len() {
                // Convert u8 back to TileType
                unsafe { std::mem::transmute::<u8, TileType>(self.tile_types[idx]) }
            } else {
                TileType::Wire
            }
        }
        #[cfg(not(feature = "gpu-prototype"))]
        {
            self.sim.get_tile_type(x, y)
        }
    }

    // Helper: Get tile value (CPU mode: from sim, GPU mode: from readback or 0)
    #[inline]
    fn get_tile_value_at(&self, x: usize, y: usize) -> u64 {
        #[cfg(feature = "gpu-prototype")]
        {
            // In GPU mode, check if we have readback data for this tile
            if let Some((rx, ry, rw, rh, ref data)) = self.last_roi_state {
                let tx = x as u32;
                let ty = y as u32;
                if tx >= rx && tx < rx + rw && ty >= ry && ty < ry + rh {
                    let local_x = tx - rx;
                    let local_y = ty - ry;
                    let idx = (local_y * rw + local_x) as usize;
                    if idx < data.len() {
                        return data[idx] as u64;
                    }
                }
            }
            0 // No readback data available
        }
        #[cfg(not(feature = "gpu-prototype"))]
        {
            self.sim.get_tile_value(x, y)
        }
    }

    fn handle_input(&mut self, dt: f32) {
        // Smooth zoom - improved responsiveness
        let wheel = mouse_wheel().1;
        if wheel != 0.0 {
            // Logarithmic zoom for consistent feel across zoom levels
            let zoom_factor = if wheel > 0.0 { 1.25 } else { 0.8 };
            self.target_zoom = (self.target_zoom * zoom_factor).clamp(MIN_ZOOM, MAX_ZOOM);
        }

        // Mouse drag pan
        if is_mouse_button_down(MouseButton::Right) {
            // Changed Pan to Right Click to free Left Click for Drawing
            let delta = mouse_delta_position();
            self.camera_pos.x -= delta.x / self.zoom;
            self.camera_pos.y -= delta.y / self.zoom;
        }

        // Mouse Draw (Left Click) - Only in Edit Mode
        if self.edit_mode && is_mouse_button_down(MouseButton::Left) {
            let mpos = mouse_position();
            let screen_w = screen_width();
            let screen_h = screen_height();
            let world_x = self.camera_pos.x + (mpos.0 - screen_w * 0.5) / self.zoom;
            let world_y = self.camera_pos.y + (mpos.1 - screen_h * 0.5) / self.zoom;
            let tile_x = (world_x / TILE_SIZE).floor() as i32;
            let tile_y = (world_y / TILE_SIZE).floor() as i32;

            if tile_x >= 0
                && tile_x < self.grid_width as i32
                && tile_y >= 0
                && tile_y < self.grid_height as i32
            {
                #[cfg(feature = "gpu-prototype")]
                if let Some(gpu) = &self.gpu_sim {
                    let type_id = match self.current_tool {
                        Tool::Wire => 0,
                        Tool::And => 1,
                        Tool::Or => 2,
                        Tool::Xor => 3,
                        Tool::Clock => 7,
                        Tool::Const => 30,
                        Tool::Not => 4,
                        Tool::CpuHead => 40,
                        Tool::Register => 41,
                        Tool::Console => 42,
                        Tool::Selector => 48,
                        Tool::Eraser => 255,
                    };
                    gpu.update_tile(tile_x as u32, tile_y as u32, type_id);

                    // If we are painting a State-carrying tile, inject a pulse!
                    // This allows the user to trigger the "Ripple" manually.
                    if type_id == 30 || type_id == 41 || type_id == 42 {
                        gpu.update_state(tile_x as u32, tile_y as u32, 255);
                    }
                }
            }
        }

        // Mouse select CPU (Left click released - for selection)
        if is_mouse_button_released(MouseButton::Left) {
            let mpos = mouse_position();
            let screen_w = screen_width();
            let screen_h = screen_height();

            // Adjust for camera center
            let world_x = self.camera_pos.x + (mpos.0 - screen_w * 0.5) / self.zoom;
            let world_y = self.camera_pos.y + (mpos.1 - screen_h * 0.5) / self.zoom;

            let tile_x = (world_x / TILE_SIZE).floor() as i32;
            let tile_y = (world_y / TILE_SIZE).floor() as i32;

            if tile_x >= 0 && tile_y >= 0 {
                #[cfg(feature = "gpu-prototype")]
                {
                    if let Some(id) = self
                        .cpu_grid
                        .get_cpu_at_tile(tile_x as usize, tile_y as usize)
                    {
                        self.selected_cpu_index = Some(id);
                        self.inspector_open = true;
                    }
                }

                #[cfg(not(feature = "gpu-prototype"))]
                {
                    let cpu_size_tiles = self.cpu_spacing as i32;
                    for (idx, cpu) in self.cpus.iter().enumerate() {
                        let (ox, oy) = cpu.cpu.origin;
                        let ox = ox as i32;
                        let oy = oy as i32;
                        if tile_x >= ox
                            && tile_x < ox + cpu_size_tiles
                            && tile_y >= oy
                            && tile_y < oy + cpu_size_tiles
                        {
                            self.selected_cpu_index = Some(idx);
                            self.inspector_open = true;
                            break;
                        }
                    }
                }
            }
        }

        // Keyboard zoom
        if is_key_down(KeyCode::Q) {
            self.target_zoom = (self.target_zoom * (1.0 + 2.0 * dt)).clamp(MIN_ZOOM, MAX_ZOOM);
        }
        if is_key_down(KeyCode::E) {
            self.target_zoom = (self.target_zoom * (1.0 - 2.0 * dt)).clamp(MIN_ZOOM, MAX_ZOOM);
        }

        // WASD pan
        let pan_amount = PAN_SPEED * dt / self.zoom;
        if is_key_down(KeyCode::W) || is_key_down(KeyCode::Up) {
            self.camera_pos.y -= pan_amount;
        }
        if is_key_down(KeyCode::S) || is_key_down(KeyCode::Down) {
            self.camera_pos.y += pan_amount;
        }
        if is_key_down(KeyCode::A) || is_key_down(KeyCode::Left) {
            self.camera_pos.x -= pan_amount;
        }
        if is_key_down(KeyCode::D) || is_key_down(KeyCode::Right) {
            self.camera_pos.x += pan_amount;
        }

        // Shortcuts
        if is_key_pressed(KeyCode::Key1) {
            self.target_zoom = 3.5;
        }
        if is_key_pressed(KeyCode::Key2) {
            self.target_zoom = 1.2;
        }
        if is_key_pressed(KeyCode::Key3) {
            self.target_zoom = 0.12;
        }
        if is_key_pressed(KeyCode::Key4) {
            self.target_zoom = 0.004;
        } // Satellite View (10k scale)
        if is_key_pressed(KeyCode::Space) {
            let center_x = (self.grid_width as f32 * TILE_SIZE) / 2.0;
            let center_y = (self.grid_height as f32 * TILE_SIZE) / 2.0;
            self.camera_pos = vec2(center_x, center_y);
            self.target_zoom = 0.05;
        }
        if is_key_pressed(KeyCode::R) {
            self.running = !self.running;
        }
        if is_key_pressed(KeyCode::F) {
            self.fullscreen = !self.fullscreen;
            set_fullscreen(self.fullscreen);
        }

        // Lerp zoom
        self.zoom = self.zoom + (self.target_zoom - self.zoom) * ZOOM_LERP_SPEED * dt;
    }

    fn should_quit(&self) -> bool {
        is_key_pressed(KeyCode::Escape)
    }

    fn update(&mut self, dt: f32) {
        self.time += dt;
        if self.running {
            #[cfg(feature = "gpu-prototype")]
            if let Some(gpu) = &mut self.gpu_sim {
                gpu.step();
                self.cycle_count += 1;
                // Don't return, let the update loop continue if we need other cpu-side effects
                // But for now, returning prevents double-sim.
                return;
            }

            // Use TRUE PHYSICS (slow but real) - CPU-only fallback
            #[cfg(not(feature = "gpu-prototype"))]
            {
                run_all_cpus(&mut self.sim, &self.cpus, 1);
                self.cycle_count += 1;
            }
        }
    }

    fn render_scene(
        &self,
        gpu_texture: Option<&Texture2D>,
        tex_offset: Vec2,
        tex_dest_size: Vec2,
        is_satellite: bool,
    ) {
        let screen_w = screen_width();
        let screen_h = screen_height();

        set_camera(&Camera2D {
            target: self.camera_pos,
            zoom: vec2(self.zoom * 2.0 / screen_w, self.zoom * 2.0 / screen_h),
            ..Default::default()
        });

        // Visible region
        let half_w = screen_w / (2.0 * self.zoom);
        let half_h = screen_h / (2.0 * self.zoom);
        let view_left = self.camera_pos.x - half_w;
        let view_right = self.camera_pos.x + half_w;
        let view_top = self.camera_pos.y - half_h;
        let view_bottom = self.camera_pos.y + half_h;

        // GPU Prototype Override
        let rendered_gpu = if let Some(tex) = gpu_texture {
            // LAYER 1: Background Layout (Rainbow Blocks)
            // Draw this BEHIND the logic texture if we are zoomed out and it is satellite view (transparency issues?)
            // Satellite texture is solid, so it covers blocks.
            // If we are in LOD_BLOCKS range, we might want to blend?

            if is_satellite && self.zoom < 0.2 {
                self.render_cpu_blocks(view_left, view_right, view_top, view_bottom);
            }

            // LAYER 2: Logic Texture (Wires & Gates)

            let params = DrawTextureParams {
                dest_size: Some(tex_dest_size),
                ..Default::default()
            };
            // tex.set_filter(FilterMode::Nearest); // Already set in main

            // For ROI, tex_offset is the world position of the top-left of the texture.
            draw_texture_ex(tex, tex_offset.x, tex_offset.y, WHITE, params);
            true
        } else {
            false
        };

        if !rendered_gpu {
            if self.zoom >= LOD_GATES {
                self.render_tiles(view_left, view_right, view_top, view_bottom);
            } else if self.zoom >= LOD_CPUS {
                self.render_cpu_blocks(view_left, view_right, view_top, view_bottom);
            } else {
                self.render_pixel_grid(view_left, view_right, view_top, view_bottom);
            }
        }
        // Note: render_cpu_blocks is already called before the texture at zoom < 0.2 (line 866-868)
        // No need to call it again here - that was causing double rendering and FPS drops

        // Only show grid when zoomed in enough to see individual cells (zoom >= 0.3)
        if self.show_grid && self.zoom >= 0.3 {
            self.render_grid_overlay(view_left, view_right, view_top, view_bottom);
        }

        // Render quantum amplitude heatmap (Sprint 57.0 Phase 5)
        // Note: This switches to screen space, so we restore world camera after
        self.render_amplitude_heatmap();

        // Restore world camera after heatmap overlay
        set_camera(&Camera2D {
            target: self.camera_pos,
            zoom: vec2(self.zoom * 2.0 / screen_w, self.zoom * 2.0 / screen_h),
            ..Default::default()
        });

        // Highlight selection
        if let Some(idx) = self.selected_cpu_index {
            #[cfg(feature = "gpu-prototype")]
            let cpu_opt = self.cpu_grid.get_cpu(idx).map(|c| (c.cpu.origin, idx));

            #[cfg(not(feature = "gpu-prototype"))]
            let cpu_opt = self.cpus.get(idx).map(|c| (c.cpu.origin, idx));

            if let Some(((ox, oy), _id)) = cpu_opt {
                let px = ox as f32 * TILE_SIZE;
                let py = oy as f32 * TILE_SIZE;
                let size = self.cpu_spacing as f32 * TILE_SIZE;
                let pulse = (self.time * 5.0).sin() * 0.5 + 0.5;
                let color = Color::new(1.0, 1.0, 0.0, 0.5 + 0.5 * pulse);
                draw_rectangle_lines(
                    px - 2.0,
                    py - 2.0,
                    size + 4.0,
                    size + 4.0,
                    4.0 / self.zoom,
                    color,
                );
            }
        }

        set_default_camera();
    }

    fn render_tiles(&self, left: f32, right: f32, top: f32, bottom: f32) {
        let tile_left = ((left / TILE_SIZE).floor() as i32).max(0) as usize;
        let tile_right =
            ((right / TILE_SIZE).ceil() as i32).clamp(0, self.grid_width as i32) as usize;
        let tile_top = ((top / TILE_SIZE).floor() as i32).max(0) as usize;
        let tile_bottom =
            ((bottom / TILE_SIZE).ceil() as i32).clamp(0, self.grid_height as i32) as usize;

        if tile_right <= tile_left || tile_bottom <= tile_top {
            return;
        }

        let tile_count = (tile_right - tile_left) * (tile_bottom - tile_top);
        let (max_tiles, step) = if self.zoom >= 0.7 {
            (25000, 1usize)
        } else {
            let max = 8000;
            let s = if tile_count > max {
                ((tile_count as f32 / max as f32).sqrt().ceil() as usize).max(1)
            } else {
                1
            };
            (max, s)
        };

        let mut drawn = 0;
        for y in (tile_top..tile_bottom).step_by(step) {
            for x in (tile_left..tile_right).step_by(step) {
                if drawn >= max_tiles {
                    return;
                }
                let tile_type = self.get_tile_type_at(x, y);
                let value = self.get_tile_value_at(x, y);
                let px = x as f32 * TILE_SIZE;
                let py = y as f32 * TILE_SIZE;
                let size = TILE_SIZE * step as f32 - 1.0;
                let color = tile_type_color(tile_type, value);
                draw_rectangle(px, py, size, size, color);
                drawn += 1;
            }
        }
    }

    // CPU-only helper (unused, kept for reference)
    #[cfg(not(feature = "gpu-prototype"))]
    #[allow(dead_code)]
    fn _draw_cpu_details(&self, ui: &mut egui::Ui, cpu: &CpuInstance) {
        let (ox, oy) = cpu.cpu.origin;
        let spacing = self.cpu_spacing;

        let cell_size = 25.0;
        let grid_width = spacing as f32 * cell_size;

        let (rect, _response) =
            ui.allocate_exact_size(egui::vec2(grid_width, grid_width), egui::Sense::hover());

        let painter = ui.painter_at(rect);

        for dy in 0..spacing {
            for dx in 0..spacing {
                let x = ox as usize + dx;
                let y = oy as usize + dy;

                let tile_type = self.get_tile_type_at(x, y);
                let value = self.get_tile_value_at(x, y);

                let mq_color = tile_type_color(tile_type, value);
                let color = egui::Color32::from_rgba_premultiplied(
                    (mq_color.r * 255.0) as u8,
                    (mq_color.g * 255.0) as u8,
                    (mq_color.b * 255.0) as u8,
                    (mq_color.a * 255.0) as u8,
                );

                let cell_rect = egui::Rect::from_min_size(
                    rect.min + egui::vec2(dx as f32 * cell_size, dy as f32 * cell_size),
                    egui::vec2(cell_size - 1.0, cell_size - 1.0),
                );

                painter.rect_filled(cell_rect, 2.0, color);

                let name = tile_type_name(tile_type);
                if !name.is_empty() {
                    painter.text(
                        cell_rect.center(),
                        egui::Align2::CENTER_CENTER,
                        name,
                        egui::FontId::proportional(10.0),
                        egui::Color32::WHITE,
                    );
                }
            }
        }
    }

    fn render_cpu_blocks(&self, left: f32, right: f32, top: f32, bottom: f32) {
        let cpu_size = self.cpu_spacing as f32 * TILE_SIZE;

        // Early exit: estimate visible CPUs - if too many, skip (GPU texture handles it)
        let visible_width = (right - left) / cpu_size;
        let visible_height = (bottom - top) / cpu_size;
        let estimated_visible = (visible_width * visible_height) as usize;

        // Don't draw individual blocks if more than 10k would be visible
        // The GPU satellite texture handles this case
        if estimated_visible > 10_000 {
            return;
        }

        // Calculate grid bounds to avoid iterating all CPUs
        let cpus_per_row = (self.grid_width / self.cpu_spacing).max(1);
        let start_col = ((left / cpu_size).floor() as usize).saturating_sub(1);
        let end_col = ((right / cpu_size).ceil() as usize) + 1;
        let start_row = ((top / cpu_size).floor() as usize).saturating_sub(1);
        let end_row = ((bottom / cpu_size).ceil() as usize) + 1;

        for row in start_row..=end_row {
            for col in start_col..=end_col {
                let idx = row * cpus_per_row + col;

                #[cfg(feature = "gpu-prototype")]
                let cpu_opt = self.cpu_grid.get_cpu(idx).map(|c| (c.cpu.origin, idx));

                #[cfg(not(feature = "gpu-prototype"))]
                let cpu_opt = self.cpus.get(idx).map(|c| (c.cpu.origin, idx));

                if let Some(((ox, oy), id)) = cpu_opt {
                    let px = ox as f32 * TILE_SIZE;
                    let py = oy as f32 * TILE_SIZE;

                    // GPU mode: use position-based color (actual state is in GPU textures)
                    // CPU mode: read from simulation
                    #[cfg(feature = "gpu-prototype")]
                    let r0 = (id % 256) as u8; // Position-based fallback

                    #[cfg(not(feature = "gpu-prototype"))]
                    let r0 = self.cpus[id].read_register(&self.sim, 0);

                    let time_pulse = if self.running { self.time * 2.0 } else { 0.0 };
                    let color = cpu_color(r0, idx, time_pulse);
                    draw_rectangle(px + 2.0, py + 2.0, cpu_size - 4.0, cpu_size - 4.0, color);

                    if self.zoom >= 0.08 {
                        let border_color =
                            Color::new(color.r * 0.5, color.g * 0.5, color.b * 0.5, 0.8);
                        draw_rectangle_lines(
                            px + 2.0,
                            py + 2.0,
                            cpu_size - 4.0,
                            cpu_size - 4.0,
                            2.0,
                            border_color,
                        );
                    }
                }
            }
        }
    }

    fn render_pixel_grid(&self, left: f32, right: f32, top: f32, bottom: f32) {
        let cpu_size = self.cpu_spacing as f32 * TILE_SIZE;

        // Early exit for satellite mode - GPU texture handles it
        let visible_width = (right - left) / cpu_size;
        let visible_height = (bottom - top) / cpu_size;
        let estimated_visible = (visible_width * visible_height) as usize;
        if estimated_visible > 10_000 {
            return;
        }

        // Use spatial indexing instead of iterating all CPUs
        let cpus_per_row = (self.grid_width / self.cpu_spacing).max(1);
        let start_col = ((left / cpu_size).floor() as usize).saturating_sub(1);
        let end_col = ((right / cpu_size).ceil() as usize) + 1;
        let start_row = ((top / cpu_size).floor() as usize).saturating_sub(1);
        let end_row = ((bottom / cpu_size).ceil() as usize) + 1;

        for row in start_row..=end_row {
            for col in start_col..=end_col {
                let idx = row * cpus_per_row + col;

                #[cfg(feature = "gpu-prototype")]
                let cpu_opt = self.cpu_grid.get_cpu(idx).map(|c| (c.cpu.origin, idx));

                #[cfg(not(feature = "gpu-prototype"))]
                let cpu_opt = self.cpus.get(idx).map(|c| (c.cpu.origin, idx));

                if let Some(((ox, oy), id)) = cpu_opt {
                    let px = ox as f32 * TILE_SIZE;
                    let py = oy as f32 * TILE_SIZE;

                    // GPU mode: use position-based color
                    #[cfg(feature = "gpu-prototype")]
                    let r0 = (id % 256) as u8;

                    #[cfg(not(feature = "gpu-prototype"))]
                    let r0 = self.cpus[id].read_register(&self.sim, 0);

                    draw_rectangle(px, py, cpu_size, cpu_size, value_to_heat(r0));
                }
            }
        }
    }

    fn render_grid_overlay(&self, left: f32, right: f32, top: f32, bottom: f32) {
        let cpu_size = self.cpu_spacing as f32 * TILE_SIZE;
        let start_x = ((left / cpu_size).floor() * cpu_size).max(0.0);
        let start_y = ((top / cpu_size).floor() * cpu_size).max(0.0);
        let end_x = right.min(self.grid_width as f32 * TILE_SIZE);
        let end_y = bottom.min(self.grid_height as f32 * TILE_SIZE);
        let mut x = start_x;
        let max = 100;
        let mut count = 0;
        while x <= end_x && count < max {
            draw_line(x, start_y, x, end_y, 1.0 / self.zoom, GRID_COLOR);
            x += cpu_size;
            count += 1;
        }
        let mut y = start_y;
        count = 0;
        while y <= end_y && count < max {
            draw_line(start_x, y, end_x, y, 1.0 / self.zoom, GRID_COLOR);
            y += cpu_size;
            count += 1;
        }
    }

    /// Render quantum amplitude heatmap overlay (Sprint 57.0 Phase 5)
    /// This renders in SCREEN SPACE as an overlay panel (bottom-right corner)
    fn render_amplitude_heatmap(&self) {
        if !self.show_amplitude_heatmap {
            return;
        }

        let Some(ref grid) = self.quantum_grid else {
            return;
        };

        let Some(ref top_blocks) = self.heatmap_cached_probs else {
            return;
        };

        if top_blocks.is_empty() {
            return;
        }

        let max_prob = top_blocks[0].1;
        if max_prob <= 0.0 {
            return;
        }

        // Switch to screen space for overlay rendering
        set_default_camera();

        // Panel position (bottom-right corner)
        let panel_margin = 10.0;
        let panel_width = 220.0;
        let panel_height = 200.0;
        let panel_x = screen_width() - panel_width - panel_margin;
        let panel_y = screen_height() - panel_height - panel_margin;

        // Panel background
        draw_rectangle(
            panel_x - 5.0,
            panel_y - 25.0,
            panel_width + 10.0,
            panel_height + 30.0,
            Color::new(0.0, 0.0, 0.0, 0.85),
        );

        // Title
        draw_text("Amplitude Heatmap", panel_x, panel_y - 5.0, 16.0, WHITE);

        // Calculate heatmap grid layout
        let num_blocks = grid.num_blocks();
        let blocks_per_row = (num_blocks as f64).sqrt().ceil() as usize;
        let heatmap_size = panel_width.min(panel_height - 60.0);
        let block_size = (heatmap_size / blocks_per_row as f32).max(1.0);

        // Draw heatmap grid
        let heatmap_x = panel_x;
        let heatmap_y = panel_y;

        for &(block_idx, prob) in top_blocks.iter() {
            if prob <= 0.0 {
                continue;
            }

            let bx = block_idx % blocks_per_row;
            let by = block_idx / blocks_per_row;

            let px = heatmap_x + bx as f32 * block_size;
            let py = heatmap_y + by as f32 * block_size;

            let color = probability_to_color(prob, max_prob, self.heatmap_log_scale);
            let size = (block_size - 0.5).max(1.0);
            draw_rectangle(px, py, size, size, color);
        }

        // Draw legend bar below heatmap
        let legend_y = panel_y + heatmap_size + 15.0;
        let legend_w = panel_width;
        let legend_h = 15.0;

        // Gradient bar
        for i in 0..legend_w as usize {
            let t = i as f64 / legend_w as f64;
            let prob = if self.heatmap_log_scale {
                max_prob * (10.0_f64).powf(-15.0 * (1.0 - t))
            } else {
                max_prob * t
            };
            let color = probability_to_color(prob, max_prob, self.heatmap_log_scale);
            draw_line(
                panel_x + i as f32,
                legend_y,
                panel_x + i as f32,
                legend_y + legend_h,
                1.0,
                color,
            );
        }

        // Labels
        draw_text("0", panel_x, legend_y + legend_h + 12.0, 12.0, WHITE);
        draw_text(
            &format!("{:.1e}", max_prob),
            panel_x + legend_w - 45.0,
            legend_y + legend_h + 12.0,
            12.0,
            WHITE,
        );

        // Stats line
        let non_zero = top_blocks.iter().filter(|(_, p)| *p > 0.0).count();
        draw_text(
            &format!("{} blocks | {} non-zero", num_blocks, non_zero),
            panel_x,
            legend_y + legend_h + 28.0,
            11.0,
            Color::new(0.7, 0.7, 0.7, 1.0),
        );
    }

    fn draw_ui_content(&mut self, ctx: &egui::Context) {
        egui::Window::new("TILE-8 Control Center")
            .default_pos(egui::pos2(10.0, 10.0))
            .show(ctx, |ui| {
                ui.heading("Simulation Controls");

                ui.horizontal(|ui| {
                    if ui
                        .button(if self.running { "⏸ Pause" } else { "▶ Run" })
                        .clicked()
                    {
                        self.running = !self.running;
                    }
                    if ui.button("Step").clicked() {
                        #[cfg(not(feature = "gpu-prototype"))]
                        {
                            run_all_cpus_fast(&mut self.sim, &self.cpus, 1);
                        }
                        #[cfg(feature = "gpu-prototype")]
                        {
                            if let Some(gpu) = &mut self.gpu_sim {
                                gpu.step();
                            }
                        }
                        self.cycle_count += 1;
                    }
                });

                ui.label(format!(
                    "Cycles: {}",
                    format_thousands(self.cycle_count as usize)
                ));
                ui.label(format!("FPS: {}", get_fps()));

                // Calculate Throughput (uses actual speed_multiplier)
                let fps = get_fps() as f64;
                let tiles = (self.grid_width * self.grid_height) as f64;
                let steps_per_frame = if self.running {
                    self.speed_multiplier as f64
                } else {
                    0.0
                };
                let evals_per_sec = tiles * fps * steps_per_frame;
                if evals_per_sec >= 1e12 {
                    ui.label(format!(
                        "Throughput: {:.2}T evals/sec",
                        evals_per_sec / 1e12
                    ));
                } else {
                    ui.label(format!("Throughput: {:.2}B evals/sec", evals_per_sec / 1e9));
                }
                if self.running && self.speed_multiplier > 1 {
                    ui.label(format!("({} steps/frame)", self.speed_multiplier));
                }

                ui.separator();
                ui.label("Speed (Cycles/Frame):");
                ui.add(egui::Slider::new(&mut self.speed_multiplier, 1..=500));

                ui.separator();
                ui.label("Zoom Level:");
                ui.add(
                    egui::Slider::new(&mut self.target_zoom, MIN_ZOOM..=MAX_ZOOM).logarithmic(true),
                );

                ui.horizontal(|ui| {
                    if ui.button("Gates").clicked() {
                        self.target_zoom = 3.5;
                    }
                    if ui.button("CPUs").clicked() {
                        self.target_zoom = 1.2;
                    }
                    if ui.button("Grid").clicked() {
                        self.target_zoom = 0.12;
                    }
                    if ui.button("Full").clicked() {
                        self.target_zoom = 0.015;
                    }
                });

                if ui.button("Reset Camera").clicked() {
                    let cx = (self.grid_width as f32 * TILE_SIZE) / 2.0;
                    let cy = (self.grid_height as f32 * TILE_SIZE) / 2.0;
                    self.camera_pos = vec2(cx, cy);
                    self.target_zoom = 0.05;
                }
                ui.separator();
                ui.label("GPU Tools:");
                ui.horizontal_wrapped(|ui| {
                    if ui.button("Wire").clicked() {
                        self.current_tool = Tool::Wire;
                    }
                    if ui.button("AND").clicked() {
                        self.current_tool = Tool::And;
                    }
                    if ui.button("OR").clicked() {
                        self.current_tool = Tool::Or;
                    }
                    if ui.button("XOR").clicked() {
                        self.current_tool = Tool::Xor;
                    }
                    if ui.button("NOT").clicked() {
                        self.current_tool = Tool::Not;
                    }
                    if ui.button("Clock").clicked() {
                        self.current_tool = Tool::Clock;
                    }
                    if ui.button("CONST").clicked() {
                        self.current_tool = Tool::Const;
                    }
                    if ui.button("CPU").clicked() {
                        self.current_tool = Tool::CpuHead;
                    }
                    if ui.button("REG").clicked() {
                        self.current_tool = Tool::Register;
                    }
                    if ui.button("OUT").clicked() {
                        self.current_tool = Tool::Console;
                    }
                    if ui.button("SEL").clicked() {
                        self.current_tool = Tool::Selector;
                    }
                    if ui.button("Eraser").clicked() {
                        self.current_tool = Tool::Eraser;
                    }
                });
                ui.label(format!("Active: {:?}", self.current_tool));

                ui.separator();
                ui.checkbox(&mut self.edit_mode, "Edit Mode");
                if self.edit_mode {
                    ui.label("Left Click to Draw");
                } else {
                    ui.label("Left Click to Select CPU");
                }

                ui.separator();
                ui.collapsing("Code Editor", |ui| {
                    ui.label("Assembly (MOV, ADD, JMP, OUT)");
                    ui.add(egui::TextEdit::multiline(&mut self.code_source).code_editor());

                    if ui.button("Compile & Upload").clicked() {
                        match assembler::assemble(&self.code_source) {
                            Ok(binary) => {
                                #[cfg(feature = "gpu-prototype")]
                                if let Some(gpu) = &self.gpu_sim {
                                    // Assembler output is already in GPU format
                                    gpu.load_rom_compiled(&binary);
                                }
                                println!(
                                    "Uploaded {} instructions ({} bytes).",
                                    binary.len() / 4,
                                    binary.len()
                                );
                            }
                            Err(e) => {
                                println!("Assembler Error: {}", e);
                            }
                        }
                    }
                });

                ui.separator();
                ui.checkbox(&mut self.show_grid, "Show Grid");

                // =====================================================================
                // QUANTUM SIMULATION PANEL (f64 precision - 100% fidelity)
                // =====================================================================
                ui.separator();
                ui.collapsing("⚛ Quantum Simulation", |ui| {
                    ui.label("F64 Precision (100% Fidelity)");

                    ui.horizontal(|ui| {
                        ui.label("Qubits:");
                        ui.add(egui::Slider::new(&mut self.quantum_n_qubits, 7..=30));
                    });

                    // Calculate memory estimate
                    let n = self.quantum_n_qubits;
                    let num_blocks = if n >= 7 { 1usize << (n - 7) } else { 1 };
                    let memory_kb = num_blocks * 2; // 2KB per block (128 Complex64)
                    let memory_str = if memory_kb < 1024 {
                        format!("{} KB", memory_kb)
                    } else if memory_kb < 1024 * 1024 {
                        format!("{:.1} MB", memory_kb as f64 / 1024.0)
                    } else {
                        format!("{:.2} GB", memory_kb as f64 / (1024.0 * 1024.0))
                    };
                    ui.label(format!("Blocks: {} | Memory: {}", num_blocks, memory_str));

                    ui.horizontal(|ui| {
                        if ui.button("Create GHZ State").clicked() {
                            let mut grid = QuantumGridF64::new(self.quantum_n_qubits);
                            let time_us = grid.create_ghz_state();
                            let verification = grid.verify_ghz_fidelity();
                            println!(
                                "GHZ-{}: Fidelity={:.6}%, Time={}μs",
                                self.quantum_n_qubits,
                                verification.fidelity * 100.0,
                                time_us
                            );
                            self.quantum_verification = Some(verification);
                            self.quantum_grid = Some(grid);
                        }

                        if ui.button("Clear").clicked() {
                            self.quantum_grid = None;
                            self.quantum_verification = None;
                        }
                    });

                    // Show verification results
                    if let Some(ref v) = self.quantum_verification {
                        ui.separator();
                        ui.label(format!("Fidelity: {:.10}%", v.fidelity * 100.0));
                        ui.label(format!("|0...0⟩: {:.8}", v.amp_zero_state));
                        ui.label(format!("|1...1⟩: {:.8}", v.amp_one_state));
                        ui.label(format!("P(0) + P(1): {:.10}", v.total_prob));
                        ui.label(format!("Max Spurious: {:.2e}", v.max_spurious));
                        ui.label(format!("Active Blocks: {}", v.active_blocks));

                        // Fidelity bar
                        let fidelity_color = if v.fidelity > 0.9999 {
                            egui::Color32::from_rgb(0, 255, 0)
                        } else if v.fidelity > 0.99 {
                            egui::Color32::from_rgb(255, 255, 0)
                        } else {
                            egui::Color32::from_rgb(255, 0, 0)
                        };
                        ui.horizontal(|ui| {
                            ui.label("Quality:");
                            let (rect, _) = ui
                                .allocate_exact_size(egui::vec2(100.0, 16.0), egui::Sense::hover());
                            let painter = ui.painter_at(rect);
                            painter.rect_filled(rect, 3.0, egui::Color32::DARK_GRAY);
                            let fill_width = rect.width() * v.fidelity as f32;
                            let fill_rect = egui::Rect::from_min_size(
                                rect.min,
                                egui::vec2(fill_width, rect.height()),
                            );
                            painter.rect_filled(fill_rect, 3.0, fidelity_color);
                        });
                    }

                    // Amplitude Heatmap Controls (Sprint 57.0 Phase 5)
                    if self.quantum_grid.is_some() {
                        ui.separator();
                        ui.label("Amplitude Heatmap");

                        ui.checkbox(&mut self.show_amplitude_heatmap, "Show Heatmap");

                        if self.show_amplitude_heatmap {
                            ui.checkbox(&mut self.heatmap_log_scale, "Log Scale");
                            ui.horizontal(|ui| {
                                ui.label("Top N blocks:");
                                ui.add(egui::Slider::new(&mut self.heatmap_top_n, 10..=1000));
                            });

                            if ui.button("Refresh Heatmap").clicked() {
                                if let Some(ref grid) = self.quantum_grid {
                                    self.heatmap_cached_probs =
                                        Some(grid.get_top_blocks(self.heatmap_top_n));
                                    println!("Heatmap refreshed: {} blocks", self.heatmap_top_n);
                                }
                            }

                            // Auto-refresh when creating GHZ state
                            if self.heatmap_cached_probs.is_none() {
                                if let Some(ref grid) = self.quantum_grid {
                                    self.heatmap_cached_probs =
                                        Some(grid.get_top_blocks(self.heatmap_top_n));
                                }
                            }
                        }
                    }
                });

                // =====================================================================
                // GRAPH STATE BUILDER PANEL (Sprint 57.0 Phase 4)
                // =====================================================================
                ui.separator();
                ui.collapsing("Graph States", |ui| {
                    ui.label("Cluster & Entanglement Patterns");

                    // Graph type selector
                    ui.horizontal(|ui| {
                        ui.label("Type:");
                        egui::ComboBox::from_id_salt("graph_type")
                            .selected_text(format!("{:?}", self.graph_type))
                            .show_ui(ui, |ui| {
                                ui.selectable_value(
                                    &mut self.graph_type,
                                    GraphPreset::Star,
                                    "Star (GHZ-equiv)",
                                );
                                ui.selectable_value(
                                    &mut self.graph_type,
                                    GraphPreset::Path,
                                    "Path (2 amps)",
                                );
                                ui.selectable_value(
                                    &mut self.graph_type,
                                    GraphPreset::Cycle,
                                    "Cycle (4 amps)",
                                );
                                ui.selectable_value(
                                    &mut self.graph_type,
                                    GraphPreset::Grid2D,
                                    "2D Grid (Cluster)",
                                );
                                ui.selectable_value(
                                    &mut self.graph_type,
                                    GraphPreset::Complete,
                                    "Complete (dense!)",
                                );
                                ui.selectable_value(
                                    &mut self.graph_type,
                                    GraphPreset::Hypercube,
                                    "Hypercube",
                                );
                                ui.selectable_value(
                                    &mut self.graph_type,
                                    GraphPreset::Ladder,
                                    "Ladder",
                                );
                                ui.selectable_value(
                                    &mut self.graph_type,
                                    GraphPreset::RandomER,
                                    "Random (ER)",
                                );
                            });
                    });

                    // Parameters based on graph type
                    match self.graph_type {
                        GraphPreset::Grid2D => {
                            ui.horizontal(|ui| {
                                ui.label("Rows:");
                                ui.add(egui::Slider::new(&mut self.graph_grid_rows, 2..=20));
                            });
                            ui.horizontal(|ui| {
                                ui.label("Cols:");
                                ui.add(egui::Slider::new(&mut self.graph_grid_cols, 2..=20));
                            });
                            let n = self.graph_grid_rows * self.graph_grid_cols;
                            ui.label(format!(
                                "Vertices: {} | Edges: {}",
                                n,
                                (self.graph_grid_rows - 1) * self.graph_grid_cols
                                    + self.graph_grid_rows * (self.graph_grid_cols - 1)
                            ));
                        }
                        GraphPreset::Hypercube => {
                            let dim = (self.graph_n_vertices as f64).log2().ceil() as usize;
                            ui.horizontal(|ui| {
                                ui.label("Dimension:");
                                let mut d = dim.max(1).min(10);
                                if ui.add(egui::Slider::new(&mut d, 1..=10)).changed() {
                                    self.graph_n_vertices = 1 << d;
                                }
                            });
                            ui.label(format!(
                                "Vertices: {} | Edges: {}",
                                1usize << dim,
                                dim * (1usize << (dim - 1))
                            ));
                        }
                        GraphPreset::RandomER => {
                            ui.horizontal(|ui| {
                                ui.label("Vertices:");
                                ui.add(egui::Slider::new(&mut self.graph_n_vertices, 3..=100));
                            });
                            ui.horizontal(|ui| {
                                ui.label("Edge prob:");
                                ui.add(egui::Slider::new(&mut self.graph_random_p, 0.0..=1.0));
                            });
                            ui.horizontal(|ui| {
                                ui.label("Seed:");
                                ui.add(egui::DragValue::new(&mut self.graph_random_seed));
                            });
                        }
                        GraphPreset::Ladder => {
                            ui.horizontal(|ui| {
                                ui.label("Rungs:");
                                let rungs = self.graph_n_vertices / 2;
                                let mut r = rungs.max(2).min(50);
                                if ui.add(egui::Slider::new(&mut r, 2..=50)).changed() {
                                    self.graph_n_vertices = r * 2;
                                }
                            });
                        }
                        _ => {
                            ui.horizontal(|ui| {
                                ui.label("Vertices:");
                                ui.add(egui::Slider::new(&mut self.graph_n_vertices, 2..=100));
                            });
                        }
                    }

                    // Action buttons
                    ui.horizontal(|ui| {
                        if ui.button("Build Graph").clicked() {
                            let graph = match self.graph_type {
                                GraphPreset::Star => Graph::star(self.graph_n_vertices.max(2)),
                                GraphPreset::Path => Graph::path(self.graph_n_vertices.max(2)),
                                GraphPreset::Cycle => Graph::cycle(self.graph_n_vertices.max(3)),
                                GraphPreset::Grid2D => Graph::grid_2d(
                                    self.graph_grid_rows.max(1),
                                    self.graph_grid_cols.max(1),
                                ),
                                GraphPreset::Complete => {
                                    Graph::complete(self.graph_n_vertices.max(2).min(20))
                                }
                                GraphPreset::Hypercube => {
                                    let dim = (self.graph_n_vertices as f64).log2().ceil() as usize;
                                    Graph::hypercube(dim.max(1).min(10))
                                }
                                GraphPreset::Ladder => {
                                    Graph::ladder(self.graph_n_vertices.max(4) / 2)
                                }
                                GraphPreset::RandomER => Graph::random_erdos_renyi(
                                    self.graph_n_vertices.max(2),
                                    self.graph_random_p,
                                    self.graph_random_seed,
                                ),
                            };
                            println!(
                                "Built {:?} graph: {} vertices, {} edges",
                                self.graph_type,
                                graph.n_vertices,
                                graph.num_edges()
                            );
                            self.graph_current = Some(graph);
                            self.graph_verification = None;
                        }

                        if ui.button("Clear").clicked() {
                            self.graph_current = None;
                            self.graph_verification = None;
                        }
                    });

                    // Show graph info
                    if let Some(ref g) = self.graph_current {
                        ui.separator();
                        ui.label(format!("Vertices: {}", g.n_vertices));
                        ui.label(format!("Edges: {}", g.num_edges()));
                        ui.label(format!("Max degree: {}", g.max_degree()));
                        ui.label(format!(
                            "Bipartite: {}",
                            if g.is_bipartite() { "Yes" } else { "No" }
                        ));
                        ui.label(format!(
                            "Connected: {}",
                            if g.is_connected() { "Yes" } else { "No" }
                        ));
                        ui.label(format!(
                            "Chromatic (upper): {}",
                            g.chromatic_number_upper_bound()
                        ));

                        // Estimate sparsity
                        let sparsity_hint: String = match self.graph_type {
                            GraphPreset::Star | GraphPreset::Path => "2 amplitudes".into(),
                            GraphPreset::Cycle => "4 amplitudes".into(),
                            GraphPreset::Grid2D => "O(2^min(r,c))".into(),
                            GraphPreset::Complete => format!("2^{} (dense!)", g.n_vertices - 1),
                            GraphPreset::Hypercube => "polynomial".into(),
                            GraphPreset::Ladder => "O(2^width)".into(),
                            GraphPreset::RandomER => "varies".into(),
                        };
                        ui.label(format!("Sparsity: {}", sparsity_hint));

                        // Export to QASM button
                        if ui.button("Export QASM 3.0").clicked() {
                            let qasm = graph_to_qasm3(g);
                            println!("=== QASM 3.0 Export ===\n{}", qasm);
                        }
                    }

                    // Show verification if available
                    if let Some(ref v) = self.graph_verification {
                        ui.separator();
                        ui.label(format!("Fidelity: {:.2}%", v.fidelity * 100.0));
                        ui.label(format!("Non-zero amps: {}", v.nonzero_amplitudes));
                        ui.label(format!(
                            "Stabilizers: {}/{}",
                            v.stabilizers_passed, v.total_stabilizers
                        ));
                    }
                });
            });

        // Pre-calculation to avoid borrow checker issues in closure
        let mut camera_update = None;
        // Store: (origin, cpu_id, tiles, regs)
        let mut inspector_details: Option<(
            (usize, usize),
            usize,
            Vec<((usize, usize), TileType, u64)>,
            [u8; 4],
        )> = None;

        // Grab data needed for inspector
        if self.inspector_open {
            if let Some(idx) = self.selected_cpu_index {
                #[cfg(feature = "gpu-prototype")]
                let cpu_data = self.cpu_grid.get_cpu(idx).map(|c| (c.cpu.origin, c.id));

                #[cfg(not(feature = "gpu-prototype"))]
                let cpu_data = self.cpus.get(idx).map(|c| (c.cpu.origin, c.id));

                if let Some(((ox, oy), cpu_id)) = cpu_data {
                    #[cfg(feature = "gpu-prototype")]
                    let spacing = self.cpu_spacing; // Was cpu_grid.spacing
                    #[cfg(not(feature = "gpu-prototype"))]
                    let spacing = self.cpu_spacing;

                    // Read Registers (GPU mode: use 0s, will be overridden from GPU readback)
                    #[cfg(feature = "gpu-prototype")]
                    let regs: [u8; 4] = [0, 0, 0, 0]; // Overridden from GPU readback below

                    #[cfg(not(feature = "gpu-prototype"))]
                    let regs = if let Some(cpu) = self.cpus.get(idx) {
                        [
                            cpu.read_register(&self.sim, 0),
                            cpu.read_register(&self.sim, 1),
                            cpu.read_register(&self.sim, 2),
                            cpu.read_register(&self.sim, 3),
                        ]
                    } else {
                        [0; 4]
                    };

                    // Clone tile data for rendering
                    let mut tiles = Vec::with_capacity(spacing * spacing);
                    for dy in 0..spacing {
                        for dx in 0..spacing {
                            let x = ox + dx;
                            let y = oy + dy;
                            let t = self.get_tile_type_at(x, y);
                            let v = self.get_tile_value_at(x, y);
                            tiles.push(((dx, dy), t, v));
                        }
                    }
                    inspector_details = Some(((ox, oy), cpu_id, tiles, regs));
                }
            }
        }

        if self.inspector_open {
            egui::Window::new("CPU Inspector")
                .default_pos(egui::pos2(screen_width() - 420.0, 10.0))
                .default_size(egui::vec2(400.0, 500.0))
                .open(&mut self.inspector_open)
                .show(ctx, |ui| {
                    if let Some((origin, _cpu_id, tiles, mut regs)) = inspector_details {
                        let (ox, oy) = origin;

                        // OVERRIDE Registers from GPU State if available
                        #[cfg(feature = "gpu-prototype")]
                        {
                            if let Some((rx, ry, rw, rh, ref data)) = self.last_roi_state {
                                // Helper to read from ROI buffer
                                let get_val = |tx: u32, ty: u32| -> Option<u32> {
                                    if tx >= rx && tx < rx + rw && ty >= ry && ty < ry + rh {
                                        let local_x = tx - rx;
                                        let local_y = ty - ry;
                                        let idx = (local_y * rw + local_x) as usize;
                                        if idx < data.len() {
                                            return Some(data[idx]);
                                        }
                                    }
                                    None
                                };

                                // Register positions: CPU at (ox+1, oy+1), regs at N/S/E/W of CPU
                                let cpu_x = (ox + 1) as u32;
                                let cpu_y = (oy + 1) as u32;
                                let reg_positions: [(u32, u32); 4] = [
                                    (cpu_x, cpu_y.saturating_sub(1)), // R0 = North
                                    (cpu_x, cpu_y + 1),               // R1 = South
                                    (cpu_x + 1, cpu_y),               // R2 = East
                                    (cpu_x.saturating_sub(1), cpu_y), // R3 = West
                                ];

                                let mut cpu_ip = 0;
                                if let Some(val) = get_val(cpu_x, cpu_y) {
                                    cpu_ip = val;
                                }

                                for i in 0..4 {
                                    let (tx, ty) = reg_positions[i];
                                    if let Some(val) = get_val(tx, ty) {
                                        regs[i] = val as u8;
                                    }
                                }

                                ui.heading(format!(
                                    "CPU #{}",
                                    self.selected_cpu_index.unwrap_or(0)
                                ));
                                ui.label(format!("IP: {}", cpu_ip));
                            }
                        }

                        ui.separator();
                        ui.columns(2, |cols| {
                            cols[0].label("R0");
                            cols[1].label(format!("{}", regs[0]));
                            cols[0].label("R1");
                            cols[1].label(format!("{}", regs[1]));
                            cols[0].label("R2");
                            cols[1].label(format!("{}", regs[2]));
                            cols[0].label("R3");
                            cols[1].label(format!("{}", regs[3]));
                        });

                        ui.separator();
                        ui.label(format!("Pos: ({}, {})", ox, oy));

                        if ui.button("Zoom to CPU").clicked() {
                            let px =
                                ox as f32 * TILE_SIZE + (self.cpu_spacing as f32 * TILE_SIZE) / 2.0;
                            let py =
                                oy as f32 * TILE_SIZE + (self.cpu_spacing as f32 * TILE_SIZE) / 2.0;
                            camera_update = Some((px, py));
                        }

                        ui.separator();
                        ui.label("Micro-Architecture:");

                        // Auto-scaling view
                        // Calculate available width
                        let available_width = ui.available_width();
                        let spacing = self.cpu_spacing;

                        // Fit whole grid into available width
                        let cell_size = (available_width / spacing as f32).max(10.0).min(30.0);
                        let grid_pixel_width = spacing as f32 * cell_size;

                        let (rect, _response) = ui.allocate_exact_size(
                            egui::vec2(grid_pixel_width, grid_pixel_width),
                            egui::Sense::hover(),
                        );

                        let painter = ui.painter_at(rect);

                        for ((dx, dy), tile_type, value) in tiles {
                            let mut value = value; // Shadow for mutation

                            // OVERRIDE Tile Value from GPU State
                            #[cfg(feature = "gpu-prototype")]
                            if let Some((rx, ry, rw, rh, ref data)) = self.last_roi_state {
                                let tx = ox as u32 + dx as u32;
                                let ty = oy as u32 + dy as u32;
                                if tx >= rx && tx < rx + rw && ty >= ry && ty < ry + rh {
                                    let local_x = tx - rx;
                                    let local_y = ty - ry;
                                    let idx = (local_y * rw + local_x) as usize;
                                    if idx < data.len() {
                                        value = data[idx] as u64;
                                    }
                                }
                            }

                            let mq_color = tile_type_color(tile_type, value);
                            let color = egui::Color32::from_rgba_premultiplied(
                                (mq_color.r * 255.0) as u8,
                                (mq_color.g * 255.0) as u8,
                                (mq_color.b * 255.0) as u8,
                                (mq_color.a * 255.0) as u8,
                            );
                            let cell_rect = egui::Rect::from_min_size(
                                rect.min + egui::vec2(dx as f32 * cell_size, dy as f32 * cell_size),
                                egui::vec2(cell_size - 1.0, cell_size - 1.0),
                            );
                            painter.rect_filled(cell_rect, 2.0, color);

                            // Only draw text if cell is big enough
                            if cell_size > 14.0 {
                                let name = tile_type_name(tile_type);
                                if !name.is_empty() {
                                    painter.text(
                                        cell_rect.center(),
                                        egui::Align2::CENTER_CENTER,
                                        name,
                                        egui::FontId::proportional(cell_size * 0.4),
                                        egui::Color32::WHITE,
                                    );
                                }
                            }
                        }
                    } else {
                        ui.label("No CPU Selected");
                    }
                });
        }

        if let Some((px, py)) = camera_update {
            self.camera_pos = vec2(px, py);
            self.target_zoom = 1.5;
        }
    }

    fn world_to_screen(&self, world_pos: Vec2) -> Vec2 {
        let screen_w = screen_width();
        let screen_h = screen_height();
        let x = (world_pos.x - self.camera_pos.x) * self.zoom + screen_w * 0.5;
        let y = (world_pos.y - self.camera_pos.y) * self.zoom + screen_h * 0.5;
        vec2(x, y)
    }

    #[cfg(feature = "gpu-prototype")]
    fn render_overlays_gpu(&self, state: &[u32], roi_x: u32, roi_y: u32, roi_w: u32, roi_h: u32) {
        // Only render if zoomed in enough
        if self.zoom < 0.2 {
            return;
        }

        let font_size = (20.0f32 * self.zoom).clamp(10.0f32, 50.0f32);
        let cyan_color = Color::new(0.0, 1.0, 1.0, 1.0);

        // 1. Spatial Lookup: Only iterate CPUs in the current ROI
        let spacing = self.cpu_spacing;
        let start_col = (roi_x as usize / spacing).saturating_sub(1);
        let end_col = ((roi_x + roi_w) as usize / spacing) + 1;
        let start_row = (roi_y as usize / spacing).saturating_sub(1);
        let end_row = ((roi_y + roi_h) as usize / spacing) + 1;

        let cpus_per_row = (self.grid_width / spacing).max(1);

        for row in start_row..end_row {
            for col in start_col..end_col {
                let id = row * cpus_per_row + col;
                if let Some(cpu) = self.cpu_grid.get_cpu(id) {
                    let (ox, oy) = cpu.cpu.origin;

                    // Check if inside ROI
                    let ox_u32 = ox as u32;
                    let oy_u32 = oy as u32;
                    if ox_u32 >= roi_x
                        && ox_u32 < roi_x + roi_w
                        && oy_u32 >= roi_y
                        && oy_u32 < roi_y + roi_h
                    {
                        let local_x = ox_u32 - roi_x;
                        let local_y = oy_u32 - roi_y;
                        let idx = (local_y * roi_w + local_x) as usize;

                        if idx < state.len() {
                            let ip = state[idx];
                            let screen_pos = self.world_to_screen(vec2(
                                ox as f32 * TILE_SIZE,
                                oy as f32 * TILE_SIZE,
                            ));
                            // Cull offscreen
                            if screen_pos.x > -100.0
                                && screen_pos.x < screen_width() + 100.0
                                && screen_pos.y > -100.0
                                && screen_pos.y < screen_height() + 100.0
                            {
                                draw_text(
                                    &format!("IP:{}", ip),
                                    screen_pos.x,
                                    screen_pos.y - 10.0,
                                    font_size,
                                    WHITE,
                                );
                            }

                            // Visualize Registers (North/South/East/West)
                            // R0 usually at (1,1) relative?
                            // Let's use cpu.registers metadata

                            for (i, reg_coord) in cpu.cpu.regs.iter().enumerate() {
                                let (rdx, rdy) = reg_coord;
                                let tx = *rdx as u32;
                                let ty = *rdy as u32;

                                if tx >= roi_x
                                    && tx < roi_x + roi_w
                                    && ty >= roi_y
                                    && ty < roi_y + roi_h
                                {
                                    let l_x = tx - roi_x;
                                    let l_y = ty - roi_y;
                                    let r_idx = (l_y * roi_w + l_x) as usize;
                                    if r_idx < state.len() {
                                        let val = state[r_idx];
                                        // Draw if > 0
                                        if val > 0 || i == 0 {
                                            // Always show R0
                                            let r_pos = self.world_to_screen(vec2(
                                                tx as f32 * TILE_SIZE,
                                                ty as f32 * TILE_SIZE,
                                            ));
                                            draw_text(
                                                &format!("{}", val),
                                                r_pos.x,
                                                r_pos.y + 15.0,
                                                font_size,
                                                cyan_color,
                                            );
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    fn _render_overlays_legacy(&self, _state: &[u32]) {
        // ... legacy code ...
    }
}

// =============================================================================
// Main
// =============================================================================

fn window_conf() -> Conf {
    Conf {
        window_title: "TILE-8 Visualizer".to_string(),
        window_width: 1600,
        window_height: 900,
        window_resizable: true,
        high_dpi: true,
        ..Default::default()
    }
}

#[macroquad::main(window_conf)]
async fn main() {
    // Parse arguments: --benchmark, --size <N>, or --selector
    let args: Vec<String> = std::env::args().collect();
    let mut cpu_count = 10_000;
    let mut spacing = 2; // GPU layout is 3x3, spacing=2 means shared registers (Hive!)
    let mut run_benchmark = false;
    let mut selector_mode = false;

    for i in 0..args.len() {
        if args[i] == "--benchmark" {
            // DENSE HIVE: Every CPU is connected! 12288/2 = 6144x6144 = 37.7 MILLION CPUs
            cpu_count = 37_748_736;
            spacing = 2;
            run_benchmark = true;
            println!("Benchmark Mode: 37.7M CPUs in 151M tiles (PERFECT MESH HIVE!)");
        }
        if args[i] == "--size" && i + 1 < args.len() {
            if let Ok(n) = args[i + 1].parse::<usize>() {
                cpu_count = n;
            }
        }
        if args[i] == "--selector" {
            selector_mode = true;
            println!("Selector Mode: Fitness-based evolutionary selection (Sprint 66)");
        }
    }

    println!("Initializing {} CPUs...", format_thousands(cpu_count));
    let mut viz = Visualizer::new_with_mode(cpu_count, spacing, selector_mode).await;

    if run_benchmark {
        // Position camera to see something interesting
        viz.target_zoom = 0.005;
        // viz.running = true; // Start running immediately
    }

    #[cfg(feature = "gpu-prototype")]
    let mut gpu_texture: Option<Texture2D> = None;

    loop {
        let dt = get_frame_time();
        clear_background(BG_COLOR);

        let mut captured = false;

        // 1. Run UI Logic
        egui_macroquad::ui(|ctx| {
            captured = ctx.wants_pointer_input() || ctx.wants_keyboard_input();
            viz.draw_ui_content(ctx);
        });

        // 2. Handle Scene Inputs
        if !captured {
            viz.handle_input(dt);
        }

        if viz.should_quit() {
            break;
        }

        // 3. Update & Render Scene
        let mut sim_start = 0.0;
        let mut sim_duration = 0.0;

        let steps_per_frame = if viz.running { viz.speed_multiplier } else { 1 };

        if viz.running {
            for _ in 0..steps_per_frame {
                viz.update(dt);
            }
        } else {
            viz.update(dt);
        }

        // --- RENDER PREP (LOD SYSTEM) ---
        let mut tex_offset = vec2(0.0, 0.0);
        let mut tex_dest_size = vec2(
            viz.grid_width as f32 * TILE_SIZE,
            viz.grid_height as f32 * TILE_SIZE,
        );
        let mut is_satellite = false;

        #[cfg(feature = "gpu-prototype")]
        {
            if let Some(gpu) = &viz.gpu_sim {
                // Determine Viewport
                let screen_w = screen_width();
                let screen_h = screen_height();
                let half_w = screen_w / (2.0 * viz.zoom * TILE_SIZE);
                let half_h = screen_h / (2.0 * viz.zoom * TILE_SIZE);
                let center_x = viz.camera_pos.x / TILE_SIZE;
                let center_y = viz.camera_pos.y / TILE_SIZE;

                let view_x = (center_x - half_w).floor() as i32;
                let view_y = (center_y - half_h).floor() as i32;
                let view_w = (half_w * 2.0).ceil() as i32;
                let view_h = (half_h * 2.0).ceil() as i32;

                // Threshold: If we see more than ~2000 tiles wide, switch to Satellite
                let use_satellite = viz.zoom < 0.05;

                if use_satellite {
                    is_satellite = true;

                    // Satellite Readback
                    if viz.running {
                        gpu.downsample();
                    }
                    let frame_bytes = gpu.capture_satellite().await;
                    let image = Image {
                        width: 4096,
                        height: 4096,
                        bytes: frame_bytes,
                    };

                    // Reuse satellite texture if it exists
                    if let Some(tex) = &viz.cached_satellite_texture {
                        tex.update(&image);
                    } else {
                        let texture = Texture2D::from_image(&image);
                        texture.set_filter(FilterMode::Linear);
                        viz.cached_satellite_texture = Some(texture);
                    }

                    // Use cached satellite texture (always maps to full grid)
                    gpu_texture = viz.cached_satellite_texture.clone();
                    tex_offset = vec2(0.0, 0.0);
                    tex_dest_size = vec2(
                        viz.grid_width as f32 * TILE_SIZE,
                        viz.grid_height as f32 * TILE_SIZE,
                    );
                } else {
                    // Detail Mode (ROI)
                    let x = view_x.max(0) as u32;
                    let y = view_y.max(0) as u32;
                    // Clamp to max texture size (4096) AND grid dimensions (to match capture return size)
                    let w = view_w
                        .clamp(1, 4096) // Limit to 4k texture
                        .min(viz.grid_width as i32 - x as i32)
                        .max(1) as u32;
                    let h = view_h
                        .clamp(1, 4096)
                        .min(viz.grid_height as i32 - y as i32)
                        .max(1) as u32;

                    // Always readback in detail mode (Original behavior)
                    let frame_bytes = gpu.capture_frame_roi(x, y, w, h).await;
                    let state_data = gpu.capture_state_roi(x, y, w, h).await;

                    if !frame_bytes.is_empty() {
                        let image = Image {
                            width: w as u16,
                            height: h as u16,
                            bytes: frame_bytes,
                        };

                        // Reuse ROI texture if dimensions match
                        let mut reused = false;
                        if let Some(tex) = &viz.cached_roi_texture {
                            if tex.width() == image.width as f32
                                && tex.height() == image.height as f32
                            {
                                tex.update(&image);
                                reused = true;
                            }
                        }

                        if !reused {
                            let texture = Texture2D::from_image(&image);
                            texture.set_filter(FilterMode::Nearest);
                            viz.cached_roi_texture = Some(texture);
                        }

                        // Register text overlays disabled - too janky and kills FPS
                        // viz.render_overlays_gpu(&state_data, x, y, w, h);
                        viz.last_roi_state = Some((x, y, w, h, state_data));
                    }

                    gpu_texture = viz.cached_roi_texture.clone();
                    tex_offset = vec2(x as f32 * TILE_SIZE, y as f32 * TILE_SIZE);
                    tex_dest_size = vec2(w as f32 * TILE_SIZE, h as f32 * TILE_SIZE);
                }
            }
        }

        #[cfg(feature = "gpu-prototype")]
        viz.render_scene(
            gpu_texture.as_ref(),
            tex_offset,
            tex_dest_size,
            is_satellite,
        );

        #[cfg(not(feature = "gpu-prototype"))]
        viz.render_scene(None, tex_offset, tex_dest_size, false);

        // 4. Draw UI
        egui_macroquad::draw();

        next_frame().await
    }
}
