//! CPU Components - ALU operations and control signals
//!
//! This module defines the logical components of the CPU. These are not
//! software implementations - they describe what the tiles should compute.

use crate::tile_meta::TileType;

/// ALU operation codes
///
/// These map to specific ALU tile configurations:
/// - Each operation uses different tiles (Add, Sub, And, Or, Xor)
/// - The control unit generates mux selects to choose the result
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum AluOp {
    /// Pass through A input unchanged
    PassA = 0,
    /// Pass through B input unchanged
    PassB = 1,
    /// A + B (wrapping)
    Add = 2,
    /// A - B (wrapping)
    Sub = 3,
    /// A & B (bitwise AND)
    And = 4,
    /// A | B (bitwise OR)
    Or = 5,
    /// A ^ B (bitwise XOR)
    Xor = 6,
    /// ~A (bitwise NOT)
    Not = 7,
    /// A << 1
    Shl = 8,
    /// A >> 1
    Shr = 9,
}

impl AluOp {
    /// Get the primary tile type for this operation
    pub fn tile_type(self) -> TileType {
        match self {
            AluOp::PassA | AluOp::PassB => TileType::Wire,
            AluOp::Add => TileType::Add,
            AluOp::Sub => TileType::Sub,
            AluOp::And => TileType::And,
            AluOp::Or => TileType::Or,
            AluOp::Xor => TileType::Xor,
            AluOp::Not => TileType::Not,
            AluOp::Shl => TileType::Shl,
            AluOp::Shr => TileType::Shr,
        }
    }

    /// Get propagation delay for this operation
    pub fn delay(self) -> u8 {
        self.tile_type().propagation_delay()
    }

    /// Decode ALU operation from instruction opcode
    pub fn from_opcode(opcode: u8) -> Self {
        match opcode {
            0x1 => AluOp::PassB,   // LDI - pass immediate
            0x2 => AluOp::PassB,   // MOV - pass source reg
            0x3 => AluOp::Add,     // ADD
            0x4 => AluOp::Sub,     // SUB
            0x5 => AluOp::And,     // AND
            0x6 => AluOp::Or,      // OR
            0x7 => AluOp::Xor,     // XOR
            0x8 => AluOp::Shl,     // SHL
            0x9 => AluOp::Shr,     // SHR
            _ => AluOp::PassA,     // NOP and others
        }
    }
}

/// Control signals generated by instruction decode
///
/// These signals control the datapath muxes, register enables, and ALU.
/// In a tile-based implementation, each signal is a wire carrying 0 or MAX.
#[derive(Debug, Clone, Copy, Default)]
pub struct ControlSignals {
    /// ALU operation select
    pub alu_op: AluOp,

    /// Write result to register file
    pub reg_write_en: bool,

    /// Destination register index (0-3)
    pub reg_dst: u8,

    /// Source register A index (0-3)
    pub reg_src_a: u8,

    /// Source register B index (0-3) or immediate
    pub reg_src_b: u8,

    /// Use immediate value instead of register B
    pub use_immediate: bool,

    /// Immediate value (4-bit, sign-extended to 8)
    pub immediate: u8,

    /// Memory read enable
    pub mem_read: bool,

    /// Memory write enable
    pub mem_write: bool,

    /// Unconditional jump
    pub jump: bool,

    /// Jump if zero flag set
    pub jump_if_zero: bool,

    /// Jump if zero flag clear
    pub jump_if_not_zero: bool,

    /// Jump target (6-bit address)
    pub jump_target: u8,

    /// Update flags from ALU result
    pub update_flags: bool,
}

impl Default for AluOp {
    fn default() -> Self {
        AluOp::PassA
    }
}

impl ControlSignals {
    /// Decode instruction byte into control signals
    pub fn decode(instruction: u8) -> Self {
        let opcode = (instruction >> 4) & 0x0F;
        let rd = (instruction >> 2) & 0x03;
        let rs_or_imm = instruction & 0x03;

        let mut signals = Self::default();

        match opcode {
            0x0 => {
                // NOP - do nothing
            }
            0x1 => {
                // LDI Rd, #imm
                signals.alu_op = AluOp::PassB;
                signals.reg_write_en = true;
                signals.reg_dst = rd;
                signals.use_immediate = true;
                signals.immediate = rs_or_imm; // 2-bit immediate
            }
            0x2 => {
                // MOV Rd, Rs
                signals.alu_op = AluOp::PassB;
                signals.reg_write_en = true;
                signals.reg_dst = rd;
                signals.reg_src_b = rs_or_imm;
            }
            0x3 => {
                // ADD Rd, Rs
                signals.alu_op = AluOp::Add;
                signals.reg_write_en = true;
                signals.reg_dst = rd;
                signals.reg_src_a = rd;
                signals.reg_src_b = rs_or_imm;
                signals.update_flags = true;
            }
            0x4 => {
                // SUB Rd, Rs
                signals.alu_op = AluOp::Sub;
                signals.reg_write_en = true;
                signals.reg_dst = rd;
                signals.reg_src_a = rd;
                signals.reg_src_b = rs_or_imm;
                signals.update_flags = true;
            }
            0x5 => {
                // AND Rd, Rs
                signals.alu_op = AluOp::And;
                signals.reg_write_en = true;
                signals.reg_dst = rd;
                signals.reg_src_a = rd;
                signals.reg_src_b = rs_or_imm;
                signals.update_flags = true;
            }
            0x6 => {
                // OR Rd, Rs
                signals.alu_op = AluOp::Or;
                signals.reg_write_en = true;
                signals.reg_dst = rd;
                signals.reg_src_a = rd;
                signals.reg_src_b = rs_or_imm;
                signals.update_flags = true;
            }
            0x7 => {
                // XOR Rd, Rs
                signals.alu_op = AluOp::Xor;
                signals.reg_write_en = true;
                signals.reg_dst = rd;
                signals.reg_src_a = rd;
                signals.reg_src_b = rs_or_imm;
                signals.update_flags = true;
            }
            0x8 => {
                // SHL Rd
                signals.alu_op = AluOp::Shl;
                signals.reg_write_en = true;
                signals.reg_dst = rd;
                signals.reg_src_a = rd;
                signals.update_flags = true;
            }
            0x9 => {
                // SHR Rd
                signals.alu_op = AluOp::Shr;
                signals.reg_write_en = true;
                signals.reg_dst = rd;
                signals.reg_src_a = rd;
                signals.update_flags = true;
            }
            0xA => {
                // CMP Rd, Rs
                signals.alu_op = AluOp::Sub;
                signals.reg_src_a = rd;
                signals.reg_src_b = rs_or_imm;
                signals.update_flags = true;
                // No write - just update flags
            }
            0xB => {
                // JMP addr
                signals.jump = true;
                signals.jump_target = instruction & 0x3F;
            }
            0xC => {
                // JZ addr
                signals.jump_if_zero = true;
                signals.jump_target = instruction & 0x3F;
            }
            0xD => {
                // JNZ addr
                signals.jump_if_not_zero = true;
                signals.jump_target = instruction & 0x3F;
            }
            0xE => {
                // LD Rd
                signals.mem_read = true;
                signals.reg_write_en = true;
                signals.reg_dst = rd;
            }
            0xF => {
                // ST Rs
                signals.mem_write = true;
                signals.reg_src_b = rs_or_imm;
            }
            _ => {}
        }

        signals
    }

    /// Check if this is a branch instruction
    pub fn is_branch(&self) -> bool {
        self.jump || self.jump_if_zero || self.jump_if_not_zero
    }

    /// Check if this is a memory instruction
    pub fn is_memory(&self) -> bool {
        self.mem_read || self.mem_write
    }
}

// =============================================================================
// Tile-based Control Unit
// =============================================================================

/// Maps control signals to tile configurations
///
/// This is used by the builder to create the control unit tiles.
pub struct ControlUnitLayout {
    /// Tiles needed for opcode decode
    pub decode_tiles: usize,
    /// Tiles needed for register select
    pub reg_select_tiles: usize,
    /// Tiles needed for ALU mux control
    pub alu_mux_tiles: usize,
    /// Tiles needed for branch logic
    pub branch_tiles: usize,
}

impl ControlUnitLayout {
    /// Calculate layout for a given instruction set
    pub fn for_instruction_set() -> Self {
        Self {
            // 4-bit opcode → 16 one-hot lines = 2 Decoder3to8 tiles
            decode_tiles: 2,
            // 2-bit reg select × 2 = 2 Decoder3to8 tiles
            reg_select_tiles: 2,
            // 5 ALU ops → Mux8to1 tile
            alu_mux_tiles: 1,
            // Branch conditions: And, Or, Mux tiles
            branch_tiles: 4,
        }
    }

    pub fn total_tiles(&self) -> usize {
        self.decode_tiles + self.reg_select_tiles + self.alu_mux_tiles + self.branch_tiles
    }
}
