//! SPRINT 80 Phase 3: Tile Grid Synthesis Transpiler
//!
//! Converts a region of the tilemap into a synthesizable RustHDL module.
//! This enables exporting tile-based designs to Verilog for FPGA deployment.

use crate::tiles::tile_meta::TileType;
use std::collections::HashMap;

/// Configuration for grid synthesis
#[derive(Clone, Debug)]
pub struct GridSynthesisConfig {
    /// Target clock frequency in MHz
    pub clock_mhz: f64,
    /// Whether to generate timing constraints
    pub generate_timing: bool,
    /// Whether to flatten the hierarchy
    pub flatten: bool,
    /// Module name prefix
    pub module_prefix: String,
}

impl Default for GridSynthesisConfig {
    fn default() -> Self {
        Self {
            clock_mhz: 100.0,
            generate_timing: true,
            flatten: false,
            module_prefix: "tile_grid".to_string(),
        }
    }
}

/// A tile cell for synthesis, containing type and initial value
#[derive(Clone, Debug)]
pub struct SynthesisTile {
    pub tile_type: TileType,
    pub initial_value: u64,
}

impl Default for SynthesisTile {
    fn default() -> Self {
        Self {
            tile_type: TileType::Wire,
            initial_value: 0,
        }
    }
}

/// A 2D grid of tiles for synthesis
#[derive(Clone, Debug)]
pub struct SynthesisGrid {
    pub width: usize,
    pub height: usize,
    pub tiles: Vec<SynthesisTile>,
    pub config: GridSynthesisConfig,
}

impl SynthesisGrid {
    /// Create a new synthesis grid
    pub fn new(width: usize, height: usize) -> Self {
        Self {
            width,
            height,
            tiles: vec![SynthesisTile::default(); width * height],
            config: GridSynthesisConfig::default(),
        }
    }

    /// Get tile at (x, y)
    pub fn get(&self, x: usize, y: usize) -> Option<&SynthesisTile> {
        if x < self.width && y < self.height {
            self.tiles.get(y * self.width + x)
        } else {
            None
        }
    }

    /// Set tile at (x, y)
    pub fn set(&mut self, x: usize, y: usize, tile: SynthesisTile) {
        if x < self.width && y < self.height {
            self.tiles[y * self.width + x] = tile;
        }
    }

    /// Check if tile type needs a clock input
    fn needs_clock(tile_type: TileType) -> bool {
        matches!(
            tile_type,
            TileType::Register8
                | TileType::Latch
                | TileType::RegEnable
                | TileType::ProgramCounter
                | TileType::Ram
                | TileType::Counter
                | TileType::ClockGlobal
        )
    }

    /// Generate Verilog code for this grid
    pub fn to_verilog(&self) -> String {
        let mut verilog = String::new();
        let module_name = format!(
            "{}_{}x{}",
            self.config.module_prefix, self.width, self.height
        );

        // Module header
        verilog.push_str(&format!(
            "// Generated by TileUniverse FPGA Synthesis (SPRINT 80)\n"
        ));
        verilog.push_str(&format!("// Grid: {}x{}\n\n", self.width, self.height));
        verilog.push_str(&format!("module {} (\n", module_name));
        verilog.push_str("    input wire clk,\n");
        verilog.push_str("    input wire rst_n,\n");

        // Generate boundary inputs/outputs
        // Left edge inputs
        for y in 0..self.height {
            verilog.push_str(&format!("    input wire [63:0] left_{},\n", y));
        }
        // Top edge inputs
        for x in 0..self.width {
            verilog.push_str(&format!("    input wire [63:0] top_{},\n", x));
        }
        // Right edge outputs
        for y in 0..self.height {
            verilog.push_str(&format!("    output wire [63:0] right_{},\n", y));
        }
        // Bottom edge outputs (last one without comma)
        for x in 0..self.width {
            let comma = if x == self.width - 1 { "" } else { "," };
            verilog.push_str(&format!("    output wire [63:0] bottom_{}{}\n", x, comma));
        }
        verilog.push_str(");\n\n");

        // Internal wire declarations
        verilog.push_str("    // Internal tile output wires\n");
        for y in 0..self.height {
            for x in 0..self.width {
                verilog.push_str(&format!("    wire [63:0] tile_{}_{}_out;\n", x, y));
            }
        }
        verilog.push('\n');

        // Generate tile instances
        verilog.push_str("    // Tile instances\n");
        for y in 0..self.height {
            for x in 0..self.width {
                if let Some(tile) = self.get(x, y) {
                    let tile_verilog = self.tile_to_verilog(x, y, tile);
                    verilog.push_str(&tile_verilog);
                }
            }
        }

        // Connect boundary outputs
        verilog.push_str("\n    // Boundary output assignments\n");
        for y in 0..self.height {
            verilog.push_str(&format!(
                "    assign right_{} = tile_{}_{}_out;\n",
                y,
                self.width - 1,
                y
            ));
        }
        for x in 0..self.width {
            verilog.push_str(&format!(
                "    assign bottom_{} = tile_{}_{}_out;\n",
                x,
                x,
                self.height - 1
            ));
        }

        verilog.push_str("\nendmodule\n");
        verilog
    }

    /// Generate Verilog for a single tile
    fn tile_to_verilog(&self, x: usize, y: usize, tile: &SynthesisTile) -> String {
        let mut v = String::new();

        // Get neighbor signals
        let left = if x > 0 {
            format!("tile_{}_{}_out", x - 1, y)
        } else {
            format!("left_{}", y)
        };
        let right = if x < self.width - 1 {
            format!("tile_{}_{}_out", x + 1, y)
        } else {
            "64'h0".to_string()
        };
        let up = if y > 0 {
            format!("tile_{}_{}_out", x, y - 1)
        } else {
            format!("top_{}", x)
        };
        let down = if y < self.height - 1 {
            format!("tile_{}_{}_out", x, y + 1)
        } else {
            "64'h0".to_string()
        };

        let out = format!("tile_{}_{}_out", x, y);

        match tile.tile_type {
            // Routing
            TileType::Wire => {
                v.push_str(&format!(
                    "    assign {} = {} | {} | {} | {};\n",
                    out, left, right, up, down
                ));
            }
            TileType::WireH => {
                v.push_str(&format!("    assign {} = {} | {};\n", out, left, right));
            }
            TileType::WireV => {
                v.push_str(&format!("    assign {} = {} | {};\n", out, up, down));
            }
            TileType::WireDown => {
                v.push_str(&format!("    assign {} = {};\n", out, up));
            }
            TileType::WireRight => {
                v.push_str(&format!("    assign {} = {};\n", out, left));
            }
            TileType::Cross => {
                v.push_str(&format!(
                    "    assign {} = (({} | {}) & 64'h00000000FFFFFFFF) | (({} | {}) & 64'hFFFFFFFF00000000);\n",
                    out, left, right, up, down
                ));
            }

            // Logic gates
            TileType::And => {
                v.push_str(&format!("    assign {} = {} & {};\n", out, left, right));
            }
            TileType::Or => {
                v.push_str(&format!("    assign {} = {} | {};\n", out, left, right));
            }
            TileType::Xor => {
                v.push_str(&format!("    assign {} = {} ^ {};\n", out, left, right));
            }
            TileType::Not => {
                v.push_str(&format!("    assign {} = ~{};\n", out, left));
            }

            // Arithmetic
            TileType::Add => {
                v.push_str(&format!("    assign {} = {} + {};\n", out, left, right));
            }
            TileType::Sub => {
                v.push_str(&format!("    assign {} = {} - {};\n", out, left, right));
            }
            TileType::Mul => {
                v.push_str(&format!(
                    "    assign {} = ({} * {})[63:0];\n",
                    out, left, right
                ));
            }
            TileType::Div => {
                v.push_str(&format!(
                    "    assign {} = ({} != 0) ? {} / {} : 64'h0;\n",
                    out, right, left, right
                ));
            }
            TileType::Mod => {
                v.push_str(&format!(
                    "    assign {} = ({} != 0) ? {} % {} : 64'h0;\n",
                    out, right, left, right
                ));
            }
            TileType::Shl => {
                v.push_str(&format!(
                    "    assign {} = {} << ({}[5:0]);\n",
                    out, left, right
                ));
            }
            TileType::Shr => {
                v.push_str(&format!(
                    "    assign {} = {} >> ({}[5:0]);\n",
                    out, left, right
                ));
            }
            TileType::Neg => {
                v.push_str(&format!("    assign {} = -{};\n", out, left));
            }
            TileType::Abs => {
                v.push_str(&format!(
                    "    assign {} = {}[63] ? -{} : {};\n",
                    out, left, left, left
                ));
            }

            // Comparison
            TileType::Lt => {
                v.push_str(&format!(
                    "    assign {} = ({} < {}) ? 64'hFFFFFFFFFFFFFFFF : 64'h0;\n",
                    out, left, right
                ));
            }
            TileType::Gt => {
                v.push_str(&format!(
                    "    assign {} = ({} > {}) ? 64'hFFFFFFFFFFFFFFFF : 64'h0;\n",
                    out, left, right
                ));
            }
            TileType::Eq => {
                v.push_str(&format!(
                    "    assign {} = ({} == {}) ? 64'hFFFFFFFFFFFFFFFF : 64'h0;\n",
                    out, left, right
                ));
            }
            TileType::Neq => {
                v.push_str(&format!(
                    "    assign {} = ({} != {}) ? 64'hFFFFFFFFFFFFFFFF : 64'h0;\n",
                    out, left, right
                ));
            }
            TileType::Lte => {
                v.push_str(&format!(
                    "    assign {} = ({} <= {}) ? 64'hFFFFFFFFFFFFFFFF : 64'h0;\n",
                    out, left, right
                ));
            }
            TileType::Gte => {
                v.push_str(&format!(
                    "    assign {} = ({} >= {}) ? 64'hFFFFFFFFFFFFFFFF : 64'h0;\n",
                    out, left, right
                ));
            }
            TileType::Zero => {
                v.push_str(&format!(
                    "    assign {} = ({} == 0) ? 64'hFFFFFFFFFFFFFFFF : 64'h0;\n",
                    out, left
                ));
            }

            // Routing/Special
            TileType::Mux => {
                v.push_str(&format!(
                    "    assign {} = ({} != 0) ? {} : {};\n",
                    out, up, left, right
                ));
            }

            // Sequential elements (require registers)
            TileType::Register8 | TileType::Latch => {
                v.push_str(&format!("    reg [63:0] reg_{}_{};\n", x, y));
                v.push_str(&format!(
                    "    always @(posedge clk) reg_{}_{} <= {};\n",
                    x, y, left
                ));
                v.push_str(&format!("    assign {} = reg_{}_{};\n", out, x, y));
            }
            TileType::RegEnable => {
                v.push_str(&format!("    reg [63:0] reg_{}_{};\n", x, y));
                v.push_str(&format!(
                    "    always @(posedge clk) if ({} != 0 && {}[0]) reg_{}_{} <= {};\n",
                    up, right, x, y, left
                ));
                v.push_str(&format!("    assign {} = reg_{}_{};\n", out, x, y));
            }
            TileType::ProgramCounter => {
                v.push_str(&format!("    reg [63:0] pc_{}_{};\n", x, y));
                v.push_str(&format!(
                    "    always @(posedge clk) pc_{}_{} <= {}[0] ? {} : pc_{}_{} + 1;\n",
                    x, y, right, left, x, y
                ));
                v.push_str(&format!("    assign {} = pc_{}_{};\n", out, x, y));
            }
            TileType::Ram => {
                v.push_str(&format!("    reg [63:0] ram_{}_{};\n", x, y));
                v.push_str(&format!(
                    "    always @(posedge clk) if ({} != 0) ram_{}_{} <= {};\n",
                    up, x, y, left
                ));
                v.push_str(&format!("    assign {} = ram_{}_{};\n", out, x, y));
            }
            TileType::Counter => {
                v.push_str(&format!("    reg [63:0] cnt_{}_{};\n", x, y));
                v.push_str(&format!(
                    "    always @(posedge clk) if ({} != 0) cnt_{}_{} <= cnt_{}_{} + 1;\n",
                    up, x, y, x, y
                ));
                v.push_str(&format!("    assign {} = cnt_{}_{};\n", out, x, y));
            }
            TileType::ClockGlobal => {
                v.push_str(&format!("    reg clock_state_{}_{};\n", x, y));
                v.push_str(&format!(
                    "    always @(posedge clk) clock_state_{}_{} <= ~clock_state_{}_{};\n",
                    x, y, x, y
                ));
                v.push_str(&format!(
                    "    assign {} = clock_state_{}_{} ? 64'hFFFFFFFFFFFFFFFF : 64'h0;\n",
                    out, x, y
                ));
            }
            TileType::Const => {
                v.push_str(&format!(
                    "    assign {} = 64'h{:016X};\n",
                    out, tile.initial_value
                ));
            }

            // CPU building blocks
            TileType::Decoder3to8 => {
                v.push_str(&format!("    assign {} = 64'h1 << ({}[2:0]);\n", out, left));
            }
            TileType::Mux8to1 => {
                v.push_str(&format!(
                    "    assign {} = ({}[63:0] >> ({}[2:0] * 8)) & 64'hFF;\n",
                    out, left, right
                ));
            }
            TileType::Demux1to8 => {
                v.push_str(&format!(
                    "    assign {} = ({}[7:0]) << ({}[2:0] * 8);\n",
                    out, up, left
                ));
            }

            // Unsupported tiles pass through left input
            _ => {
                v.push_str(&format!(
                    "    // Unsupported tile type {:?} at ({}, {})\n",
                    tile.tile_type, x, y
                ));
                v.push_str(&format!("    assign {} = {};\n", out, left));
            }
        }

        v
    }

    /// Calculate total propagation delay through the critical path
    pub fn critical_path_delay(&self) -> u32 {
        // Simple estimation: sum of delays along diagonal path
        let mut max_delay = 0u32;
        for y in 0..self.height {
            for x in 0..self.width {
                if let Some(tile) = self.get(x, y) {
                    let path_delay = (x + y) as u32 + tile.tile_type.propagation_delay() as u32;
                    max_delay = max_delay.max(path_delay);
                }
            }
        }
        max_delay
    }

    /// Count tiles by type
    pub fn tile_counts(&self) -> HashMap<TileType, usize> {
        let mut counts = HashMap::new();
        for tile in &self.tiles {
            *counts.entry(tile.tile_type).or_insert(0) += 1;
        }
        counts
    }

    /// Estimate resource utilization (LUTs, FFs)
    pub fn estimate_resources(&self) -> ResourceEstimate {
        let mut luts = 0;
        let mut ffs = 0;

        for tile in &self.tiles {
            let (tile_luts, tile_ffs) = match tile.tile_type {
                // Routing
                TileType::Wire | TileType::WireH | TileType::WireV => (64, 0),
                TileType::WireDown | TileType::WireRight => (0, 0),
                TileType::Cross => (128, 0),

                // Simple gates
                TileType::And | TileType::Or | TileType::Xor | TileType::Not => (64, 0),

                // Arithmetic
                TileType::Add | TileType::Sub => (128, 0),
                TileType::Mul => (512, 0), // DSP could be used
                TileType::Div | TileType::Mod => (1024, 0),
                TileType::Shl | TileType::Shr => (256, 0),
                TileType::Neg | TileType::Abs => (128, 0),

                // Comparison
                TileType::Lt
                | TileType::Gt
                | TileType::Eq
                | TileType::Neq
                | TileType::Lte
                | TileType::Gte => (128, 0),
                TileType::Zero => (64, 0),

                // Routing/Mux
                TileType::Mux => (64, 0),
                TileType::Decoder3to8 => (8, 0),
                TileType::Mux8to1 => (64, 0),
                TileType::Demux1to8 => (64, 0),

                // Sequential
                TileType::Register8 | TileType::Latch => (0, 64),
                TileType::RegEnable => (2, 64),
                TileType::ProgramCounter => (64, 64),
                TileType::Ram => (2, 64),
                TileType::Counter => (64, 64),
                TileType::ClockGlobal => (1, 1),
                TileType::Const => (0, 0),

                // Other
                _ => (64, 0),
            };
            luts += tile_luts;
            ffs += tile_ffs;
        }

        ResourceEstimate {
            luts,
            flip_flops: ffs,
            dsps: self
                .tiles
                .iter()
                .filter(|t| t.tile_type == TileType::Mul)
                .count(),
            brams: 0,
        }
    }
}

/// Resource utilization estimate
#[derive(Clone, Debug, Default)]
pub struct ResourceEstimate {
    pub luts: usize,
    pub flip_flops: usize,
    pub dsps: usize,
    pub brams: usize,
}

impl std::fmt::Display for ResourceEstimate {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "LUTs: {}, FFs: {}, DSPs: {}, BRAMs: {}",
            self.luts, self.flip_flops, self.dsps, self.brams
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_simple_grid_synthesis() {
        let mut grid = SynthesisGrid::new(2, 2);
        grid.set(
            0,
            0,
            SynthesisTile {
                tile_type: TileType::And,
                initial_value: 0,
            },
        );
        grid.set(
            1,
            0,
            SynthesisTile {
                tile_type: TileType::Or,
                initial_value: 0,
            },
        );
        grid.set(
            0,
            1,
            SynthesisTile {
                tile_type: TileType::Wire,
                initial_value: 0,
            },
        );
        grid.set(
            1,
            1,
            SynthesisTile {
                tile_type: TileType::Xor,
                initial_value: 0,
            },
        );

        let verilog = grid.to_verilog();
        assert!(verilog.contains("module tile_grid_2x2"));
        assert!(verilog.contains("assign tile_0_0_out = left_0 & tile_1_0_out"));
        assert!(verilog.contains("assign tile_1_1_out = tile_0_1_out ^ 64'h0"));
    }

    #[test]
    fn test_sequential_synthesis() {
        let mut grid = SynthesisGrid::new(2, 1);
        grid.set(
            0,
            0,
            SynthesisTile {
                tile_type: TileType::Const,
                initial_value: 42,
            },
        );
        grid.set(
            1,
            0,
            SynthesisTile {
                tile_type: TileType::Register8,
                initial_value: 0,
            },
        );

        let verilog = grid.to_verilog();
        assert!(verilog.contains("64'h000000000000002A")); // Const 42
        assert!(verilog.contains("reg [63:0] reg_1_0"));
        assert!(verilog.contains("always @(posedge clk)"));
    }

    #[test]
    fn test_resource_estimation() {
        let mut grid = SynthesisGrid::new(4, 4);
        // Fill with mix of tiles
        for y in 0..4 {
            for x in 0..4 {
                let tile_type = match (x + y) % 4 {
                    0 => TileType::And,
                    1 => TileType::Register8,
                    2 => TileType::Add,
                    _ => TileType::Wire,
                };
                grid.set(
                    x,
                    y,
                    SynthesisTile {
                        tile_type,
                        initial_value: 0,
                    },
                );
            }
        }

        let resources = grid.estimate_resources();
        assert!(resources.luts > 0);
        assert!(resources.flip_flops > 0);
    }

    #[test]
    fn test_critical_path() {
        let mut grid = SynthesisGrid::new(3, 3);
        // Wire chain has minimal delay
        for y in 0..3 {
            for x in 0..3 {
                grid.set(
                    x,
                    y,
                    SynthesisTile {
                        tile_type: TileType::Wire,
                        initial_value: 0,
                    },
                );
            }
        }

        let delay = grid.critical_path_delay();
        // Max is at (2,2) with path 4 + wire delay 1 = 5
        assert_eq!(delay, 5);
    }
}
